S#015

diff --git a/bin/progress-dot-wrapper b/bin/progress-dot-wrapper
--- a/bin/progress-dot-wrapper
+++ b/bin/progress-dot-wrapper
@@ -5,15 +5,18 @@ if [[ $1 == '@@' ]]; then # {{{
   case $3 in
   -C | --background-cmd) echo "CMD";;
   --check-cmd)  echo "CMD";;
-  -n)     echo "1 3 5 10 15 20";;
+  -n) echo "1 3 5 10 15 20";;
   -f | --file-marker) echo "@@-f";;
   --init-p) echo "---";;
   --step) echo "1 0.5 2 5";;
   -w | --wait)  echo "1m 5m 30m";;
+  --pane) echo "PANE";;
+  --pid) echo "PID";;
   *)
     echo "--check-cmd -n -every"
     echo "--background-cmd -C"
     echo "--init-p --no-info --no-err --step -f --file-marker"
+    echo "--pane --pid"
     echo "-w --wait 1m 5m 30m";;
   esac
   exit 0
@@ -31,6 +34,9 @@ reportError=true
 showInfo=true
 fileMarker=
 step=1.0
+pid=
+pidCmd=
+exitVal=0
 
 while [[ ! -z $1 ]]; do # {{{
   case $1 in
@@ -43,45 +49,78 @@ while [[ ! -z $1 ]]; do # {{{
   --no-err) reportError=false;;
   --no-info) showInfo=false;;
   --step) step="$2"; shift;;
+  --pane) # {{{
+    pidPane="$(tmux display-message -t "$2" -pF '#{pane_pid}')"
+    [[ -n $pidPane ]] || die "cannot get pid for '$2'"
+    if $IS_MAC; then
+      pid="$(pid-tree $pidPane | sed -n 2p)"
+    else
+      pid="$(ps -g $pidPane -o "pid=" | sed -n 2p)"
+    fi
+    [[ -n $pid ]] || die "cannot get child process of $pidPane in '$2'"
+    delay="3h"
+    shift;; # }}}
+  --pid) # {{{
+    pid="$2"
+    delay="3h"
+    shift;; # }}}
   -w | --wait) delay="$2"; shift;;
   *) delay=$1;;
   esac; shift
 done # }}}
 
+if [[ -n $pid ]]; then
+  if $IS_MAC; then
+    pidCmd="ps xa -o pid= | grep -q '^\s*${pid}$'"
+  else
+    pidCmd="pgrep --quiet -p $pid"
+  fi
+fi
 [[ -z $fileMarker ]] || rm -f $fileMarker
 
 if [[ ! -z $workerCmd ]]; then # {{{
-  $workerCmd &
+  eval $workerCmd >/dev/null 2>&1 &
   workerCmdPid=$!
 fi # }}}
 
 clean-up() { # {{{
   if [[ ! -z $workerCmdPid ]]; then # {{{
-    kill $workerCmdPid 2>/dev/null
+    kill-rec $workerCmdPid 2>/dev/null
     wait $workerCmdPid
   fi # }}}
-  [[ -z $fileMarker ]] || rm -f $fileMarker
+  if [[ -n $fileMarker ]]; then
+    rm -f $fileMarker
+  fi
+  $reportError || exit 0
+  exit $exitVal
 } # }}}
-
-trap "clean-up; $reportError && exit 1 || exit 0" INT
+trap "clean-up" INT EXIT
 
 delay=$(time2s $delay -o s)
 t_end=$((EPOCHSECONDS + $delay))
-$showInfo && printfc "%ts:%s: end at %info:%s, pid: %purple:%s" "$(date +$TIME_FMT -d @$EPOCHSECONDS)" "$(date +$TIME_FMT -d @$t_end)" "$$"
+$showInfo && printfc "%ts:%s: end at %info:%s$([[ -n $pid ]] && printfc "/pid:%info:%s" $pid), pid: %purple:%s" "$(date +$TIME_FMT -d @$EPOCHSECONDS)" "$(date +$TIME_FMT -d @$t_end)" "$$"
 
 endReason="timeout"
 progress-dot --init $params --end $t_end
 for ((i=1; EPOCHSECONDS < t_end; i++)); do # {{{
   sleep-precise -s
-  if [[ ! -z $checkCmd || ! -z $fileMarker ]] && (($i % $cmd_n == 0)); then
-    [[ ! -z $fileMarker && -e $fileMarker ]] || eval $checkCmd
-    if (( $? == 0 )); then
-      progress-dot --dot=ok
+  if [[ ! -z $pidCmd || ! -z $fileMarker || ! -z $checkCmd ]] && (($i % $cmd_n == 0)); then
+    if [[ -n $pidCmd ]] && ! eval "$pidCmd" >/dev/null 2>&1; then
+      progress-dot --dot=err
+      endReason="pidCmd"; break
+    fi
+    if [[ ! -z $fileMarker && -e $fileMarker ]]; then
+      progress-dot --dot=err
+      endReason="fileMarker"; break
+    fi
+    if [[ -n $checkCmd ]] && ! eval "$checkCmd" >/dev/null 2>&1; then
+      progress-dot --dot=err
       endReason="checkCmd"; break
-    elif (( cmd_n == 1 )); then
+    fi
+    if (( cmd_n == 1 )); then
       progress-dot --dot
     else
-      progress-dot --dot=err
+      progress-dot --dot=ok
     fi
   else
     progress-dot --dot
@@ -92,16 +131,16 @@ for ((i=1; EPOCHSECONDS < t_end; i++)); do # {{{
 done # }}}
 
 case $endReason in # {{{
-checkCmd)
+checkCmd | pidCmd | fileMarker)
   progress-dot --end
-  exit 0;;
+  exitVal=0;;
 break)
   progress-dot --end=Q
-  $reportError && exit 1 || exit 0;;
+  exitVal=1;;
 timeout)
   progress-dot --end=T
-  $reportError && exit 10 || exit 0;;
+  exitVal=10;;
 *)
   progress-dot --end=?
-  exit 2;;
+  exitVal=2;;
 esac # }}}
diff --git a/bin/tmux-popup b/bin/tmux-popup
--- a/bin/tmux-popup
+++ b/bin/tmux-popup
@@ -1,146 +1,148 @@
 #!/usr/bin/env bash
 # vim: fdl=0
 
+popupPath="${TMUX_POPUP_PATH:-$APPS_CFG_PATH/tmux/popup}"
+
+if [[ $1 == '@@' ]]; then # {{{
+  case $3 in
+  --title) echo "TITLE";;
+  *) echo "-E -EE -e -t --title -c CMD --no-wait --no-show"
+    declare -A TMUX_POPUP_CMD
+    [[ -e $popupPath/.cmds ]] && source $popupPath/.cmds
+    echo "n r ${!TMUX_POPUP_CMD[*]}";;
+  esac
+  exit 0
+fi # }}}
+
+[[ -n $TMUX ]] || exit 1
+[[ $TMUX_VERSION -gt 30 ]] || die "tmux >= 3.0 is required (vs $(tmux -V))"
+
 import-module echor
 
-_tmux-popup() { # @@ # {{{
-  [[ -n $TMUX ]] || return 1
-  [[ $TMUX_VERSION -gt 30 ]] || eval $(die "tmux >= 3.0 is required (vs $(tmux -V))")
-  local popupPath="${TMUX_POPUP_PATH:-$APPS_CFG_PATH/tmux/popup}"
-  if [[ $1 == '@@' ]]; then # {{{
-    case $3 in
-    --title) echo "TITLE";;
-    *) echo "-E -EE -e -t --title -c CMD --no-wait --no-show"
-      declare -A TMUX_POPUP_CMD
-      [[ -e $popupPath/.cmds ]] && source $popupPath/.cmds
-      echo "n r ${!TMUX_POPUP_CMD[*]}";;
-    esac
-    return 0
-  fi # }}}
-  [[ -e $popupPath ]] || mkdir -p $popupPath >/dev/null
-  local tp=$TMUX_PANE cmd= params= silent=false showCmd=true name= addWait= isInteractive=true
-  while [[ ! -z $1 ]]; do # {{{
-    case $1 in
-    -E | -EE | -e) params="$1";;
-    --no-i) isInteractive=false;;
-    -t) tp=$2; shift;;
-    -c) shift; cmd="${@:-help}"; shift $#;;
-    --title) name="$2"; shift;;
-    --no-wait) addWait=false;;
-    --no-show) showCmd=false;;
-    --cmd-show) showCmd="$2";;
-    *)  cmd="$@"; shift $#;;
-    esac; shift
-  done # }}}
-  if [[ ! -z $cmd ]]; then # {{{
-    declare -A TMUX_POPUP_CMD
-    TMUX_POPUP_CMD[gb]="git backup"
-    TMUX_POPUP_CMD[gst]="git utils gitst --all -v; true # @W"
-    if which htop >/dev/null 2>&1; then
-      TMUX_POPUP_CMD[h]="htop # @NC @NW"
-    fi
-    TMUX_POPUP_CMD[n]="net -lle # @NW @NC"
-    TMUX_POPUP_CMD[N]="net # @W @NC"
-    TMUX_POPUP_CMD[r]="reminder.sh countdown -l 120 # @NC @W2"
-    TMUX_POPUP_CMD[pid]="tmux list-panes -F \"#P :: #{s| ||:pane_title} :: #{pane_pid} :: #{pane_current_command} :: #{pane_current_path}\" | column -t # @W- @NC"
-    [[ -e $popupPath/.cmds ]] && source $popupPath/.cmds
-    case $cmd in
-    help) # {{{
-      name=select
-      showCmd=false
-      params="-EE"
-      declare -p TMUX_POPUP_CMD >$TMP_MEM_PATH/tmux-popup.sh
-      cat >>$TMP_MEM_PATH/tmux-popup.sh<<-'EOF'
-				import-module echor
-				err=0
-				addWait=false
-				waitTimeout="-t5"
-				list=
-				for i in $(echo "${!TMUX_POPUP_CMD[*]}" | tr ' ' '\n' | sort); do
-				  list+="$(printf "%-5s : %s" "$i" "${TMUX_POPUP_CMD[$i]%% # *}")\n"
-				done
-				action="$(echo -e "${list%\\n}" | fzf | awk '{print $1}')"
-				[[ ! -z "$action" ]] || exit 255
-				c="${TMUX_POPUP_CMD[$action]}"
-				if false; then :
-				elif [[ $c =~ " # ".*@NW ]]; then addWait=false
-				elif [[ $c =~ " # ".*@W- ]]; then addWait=true; waitTimeout=""
-				elif [[ $c =~ " # ".*@W([0-9]+) ]]; then addWait=true; waitTimeout="-t${BASH_REMATCH[1]}"
-				elif [[ $c =~ " # ".*@W ]]; then addWait=true
-				fi
-				c="${c%% # *}"
-				eval "$c" || exit 1
-				waitCmd="{ echo; echorm --name popup -n 0 \"press a key...\"; read -s -n1 $waitTimeout; }"
-				$addWait && eval $waitCmd
-				exit 0
-				EOF
-      chmod +x $TMP_MEM_PATH/tmux-popup.sh
-      cmd="$TMP_MEM_PATH/tmux-popup.sh"
-      ;; # }}}
-    *) # {{{
-      if [[ -z $name ]]; then
-        name=${cmd%% *}
-        if [[ ! -z ${TMUX_POPUP_CMD[$name]} ]]; then
-          if [[ "$name" != "$cmd" ]]; then
-            cmd="${TMUX_POPUP_CMD[$name]} ${cmd#* }"
-          else
-            cmd=${TMUX_POPUP_CMD[$name]}
-          fi
-          name=${cmd%% *}
+[[ -e $popupPath ]] || mkdir -p $popupPath >/dev/null
+tp=$TMUX_PANE cmd= params= silent=false showCmd=true name= addWait= isInteractive=true
+while [[ ! -z $1 ]]; do # {{{
+  case $1 in
+  -E) params="$1"; addWait=false;;
+  -EE | -e) params="$1";;
+  --no-i) isInteractive=false;;
+  -t) tp=$2; shift;;
+  -c) shift; cmd="${@:-help}"; shift $#;;
+  --title) name="$2"; shift;;
+  --no-wait) addWait=false;;
+  --no-show) showCmd=false;;
+  --cmd-show) showCmd="$2";;
+  *)  cmd="$@"; shift $#;;
+  esac; shift
+done # }}}
+if [[ ! -z $cmd ]]; then # {{{
+  declare -A TMUX_POPUP_CMD
+  TMUX_POPUP_CMD[gb]="git backup"
+  TMUX_POPUP_CMD[gst]="git utils gitst --all -v; true # @W"
+  which btop >/dev/null 2>&1 && TMUX_POPUP_CMD[bt]="btop # @NC @NW"
+  which htop >/dev/null 2>&1 && TMUX_POPUP_CMD[ht]="htop # @NC @NW"
+  TMUX_POPUP_CMD[pg]="psgrep # @NW @NC"
+  TMUX_POPUP_CMD[n]="net --wait # @NW @NC"
+  TMUX_POPUP_CMD[nl]="net -lle # @NW @NC"
+  TMUX_POPUP_CMD[N]="net # @W @NC"
+  TMUX_POPUP_CMD[r]="reminder.sh countdown -l 120 # @NC @W2"
+  TMUX_POPUP_CMD[pid]="tmux list-panes -F \"#P :: #{s| ||:pane_title} :: #{pane_pid} :: #{pane_current_command} :: #{pane_current_path}\" | column -t # @W- @NC"
+  [[ -e $popupPath/.cmds ]] && source $popupPath/.cmds
+  case $cmd in
+  help) # {{{
+    name=select
+    showCmd=false
+    params="-EE"
+    declare -p TMUX_POPUP_CMD >$TMP_MEM_PATH/tmux-popup.sh
+    cat >>$TMP_MEM_PATH/tmux-popup.sh <<'EOF'
+import-module echor
+err=0
+addWait=false
+waitTimeout="-t5"
+list=
+for i in $(echo "${!TMUX_POPUP_CMD[*]}" | tr ' ' '\n' | sort); do
+  list+="$(printf "%-5s : %s" "$i" "${TMUX_POPUP_CMD[$i]%% # *}")\n"
+done
+action="$(echo -e "${list%\\n}" | fzf | awk '{print $1}')"
+[[ ! -z "$action" ]] || exit 255
+c="${TMUX_POPUP_CMD[$action]}"
+if false; then :
+elif [[ $c =~ " # ".*@NW ]]; then addWait=false
+elif [[ $c =~ " # ".*@W- ]]; then addWait=true; waitTimeout=""
+elif [[ $c =~ " # ".*@W([0-9]+) ]]; then addWait=true; waitTimeout="-t${BASH_REMATCH[1]}"
+elif [[ $c =~ " # ".*@W ]]; then addWait=true
+fi
+c="${c%% # *}"
+eval "$c" || exit 1
+waitCmd="{ echo; echorm --name popup -n 0 \"press a key...\"; read -s -n1 $waitTimeout; }"
+$addWait && eval $waitCmd
+exit 0
+EOF
+    chmod +x $TMP_MEM_PATH/tmux-popup.sh
+    cmd="$TMP_MEM_PATH/tmux-popup.sh"
+    ;; # }}}
+  *) # {{{
+    if [[ -z $name ]]; then
+      name=${cmd%% *}
+      if [[ ! -z ${TMUX_POPUP_CMD[$name]} ]]; then
+        if [[ "$name" != "$cmd" ]]; then
+          cmd="${TMUX_POPUP_CMD[$name]} ${cmd#* }"
+        else
+          cmd=${TMUX_POPUP_CMD[$name]}
         fi
+        name=${cmd%% *}
       fi
-      [[ $cmd == *sleep* ]] || addWait=${addWait:-true}
-      ;; # }}}
-    esac
-    local c="$cmd" shell=$SHELL
-    local waitTimeout="-t5"
-    [[ $IS_MAC ]] && shell=bash
-    [[ -z $addWait ]] && addWait=false
-    if false; then :
-    elif [[ $c =~ " # ".*@NW ]]; then addWait=false
-    elif [[ $c =~ " # ".*@W- ]]; then addWait=true; waitTimeout=""
-    elif [[ $c =~ " # ".*@W([0-9]+) ]]; then addWait=true; waitTimeout="-t${BASH_REMATCH[1]}"
-    elif [[ $c =~ " # ".*@W ]]; then addWait=true
     fi
-    if false; then :
-    elif [[ $c =~ " # ".*@NC ]]; then showCmd=false
-    fi
-    local waitCmd="{ echo; echorm --name popup -n 0 \"press a key...\"; read -s -n1 $waitTimeout; }"
-    c="${c%% # *}"
-    cmd="$shell -i"
-    cmd+=" -c '"
-    case $showCmd in
-    true) cmd+="(echorm --name popup 0 \"${c//\"/\\\"}\"; echo; );";;
-    false) ;;
-    *) cmd+="(echorm --name popup 0 \"${showCmd//\"/\\\"}\"; echo; );";;
-    esac
-    cmd+=" $c; err=\$?;"
-    cmd+=" (( \$err == 0 || \$err == 255 )) || { ( echorm --name popup 0 \"\$(cl err fail)\" ); };"
-    $addWait && cmd+=" (( \$err == 0 )) && $waitCmd;"
-    cmd+=" (( \$err == 0 || \$err == 255 ));"
-    cmd+="'"
-    [[ -z $params ]] && params="-EE"
-    silent=true
-  else
-    cmd="$TMUX_POPUP_SHELL"
-    [[ -z $params ]] && params="-E"
-  fi # }}}
-  [[ $params == '-e' ]] && params=
-  local p="$(tmux display-message -t $tp -p -F '#{pane_current_path}')"
-  local d="$popupPath/mem"
-  mkdir -p $TMP_MEM_PATH/${popupPath//\//-} >/dev/null
-  [[ -e $d ]] || ln -sf $TMP_MEM_PATH/${popupPath//\//-} $d
-  [[ -e $popupPath/notes.txt ]] || touch $popupPath/notes.txt
-  [[ -e $d/notes.txt ]] || ln -sf $popupPath/notes.txt $d/notes.txt
-  tmux display-popup -t $tp $params -d "$p" -w 75% -h 75% -T " ${name:-popup} " \
-    -e "TMUX_POPUP=true" \
-    -e "TMUX_POPUP_SILENT=$silent" \
-    -e "DISPLAY=$DISPLAY" \
-    -e "s=$p" \
-    -e "d=$d" \
-    -e "spane=$TMUX_PANE" \
-    "$cmd"
-  return 0
-} # }}}
-_tmux-popup "$@"
-
+    [[ $cmd == *sleep* ]] || addWait=${addWait:-true}
+    ;; # }}}
+  esac
+  c="$cmd" shell=$SHELL
+  waitTimeout="-t5"
+  [[ $IS_MAC ]] && shell=bash
+  [[ -z $addWait ]] && addWait=false
+  if false; then :
+  elif [[ $c =~ " # ".*@NW ]]; then addWait=false
+  elif [[ $c =~ " # ".*@W- ]]; then addWait=true; waitTimeout=""
+  elif [[ $c =~ " # ".*@W([0-9]+) ]]; then addWait=true; waitTimeout="-t${BASH_REMATCH[1]}"
+  elif [[ $c =~ " # ".*@W ]]; then addWait=true
+  fi
+  if false; then :
+  elif [[ $c =~ " # ".*@NC ]]; then showCmd=false
+  fi
+  waitCmd="{ echo; echorm --name popup -n 0 \"press a key...\"; read -s -n1 $waitTimeout; }"
+  c="${c%% # *}"
+  cmd="$shell -i"
+  cmd+=" -c '"
+  case $showCmd in
+  true) cmd+="(echorm --name popup 0 \"${c//\"/\\\"}\"; echo; );";;
+  false) ;;
+  *) cmd+="(echorm --name popup 0 \"${showCmd//\"/\\\"}\"; echo; );";;
+  esac
+  cmd+=" $c; err=\$?;"
+  cmd+=" (( \$err == 0 || \$err == 255 )) || { ( echorm --name popup 0 \"\$(cl err fail)\" ); };"
+  $addWait && cmd+=" (( \$err == 0 )) && $waitCmd;"
+  cmd+=" (( \$err == 0 || \$err == 255 ));"
+  cmd+="'"
+  [[ -z $params ]] && params="-EE"
+  silent=true
+else
+  cmd="$TMUX_POPUP_SHELL"
+  [[ -z $params ]] && params="-E"
+fi # }}}
+[[ $params == '-e' ]] && params=
+p="$(tmux display-message -t $tp -p -F '#{pane_current_path}')"
+d="$popupPath/mem"
+mkdir -p $TMP_MEM_PATH/${popupPath//\//-} >/dev/null
+[[ -e $d ]] || ln -sf $TMP_MEM_PATH/${popupPath//\//-} $d
+[[ -e $popupPath/notes.txt ]] || touch $popupPath/notes.txt
+[[ -e $d/notes.txt ]] || ln -sf $popupPath/notes.txt $d/notes.txt
+env_src="$(tmux display-message -p -t $tp -F '#{pid}.#{s/^\$//:#{session_id}}.#{window_id}')"
+tmux display-popup -t $tp $params -d "$p" -w 75% -h 75% -T " ${name:-popup} " \
+  -e "TMUX_POPUP=true" \
+  -e "TMUX_POPUP_SILENT=$silent" \
+  -e "DISPLAY=$DISPLAY" \
+  -e "s=$p" \
+  -e "d=$d" \
+  -e "spane=$TMUX_PANE" \
+  "$cmd"
+exit 0
