S#008
changed by purpose

diff --git a/bash/aliases.d/fzf-tools b/bash/aliases.d/fzf-tools
--- a/bash/aliases.d/fzf-tools
+++ b/bash/aliases.d/fzf-tools
@@ -58,61 +58,71 @@ fzf_exe() { # @@ # {{{
   [[ ! -e $file ]] && file="${file%-*}"
   [[ -f $file || $cmd == 'prev' ]] || { echo "Canot open [$file]" >/dev/stderr; sleep 1; return 0; }
   case $cmd in # {{{
-  less)       params="-N";;&
-  vim)        params="-cl -c FastVim -c FastClipboard";;&
-  less | vim)
-              [[ ! -z $line ]] && params+=" +$line"
-              params+=" $file"
-              ;;&
-  vim)        params+=" -c 'normal! zv' ";;
-  less)       ;;
-  prev)       [[ -z $line ]] && line='1'
-              local first_line=$(($line-$prev_lines_before))
-              [[ $first_line -lt 1 ]] && first_line='1'
-              ;;
-  pane)       local ppid=$(tmux display-message -t $pane -p -F '#{pane_pid}')
-              if ! $IS_MAC; then
-                command pstree -Ac $ppid | command grep -q -e '---vim'
-              else
-                command pstree $ppid | command grep -q -i -e 'vim'
-              fi || { echo "Vim not found in pane '$pane'" >/dev/stderr; sleep 1; return 0; }
-              ;;
-  *)          { echo "Unknown command [$cmd]" >/dev/stderr; sleep 1; return 0; };;
+  less | vim) # {{{
+    case $cmd in
+    less)       params="-N";;
+    vim)        params="-cl -c FastVim";;
+    esac
+    [[ ! -z $line ]] && params+=" +$line"
+    params+=" $file"
+    case $cmd in
+    vim)        params+=" -c 'normal! zv' ";;
+    esac;; # }}}
+  prev) # {{{
+    [[ -z $line ]] && line='1'
+    local first_line=$(($line-$prev_lines_before))
+    [[ $first_line -lt 1 ]] && first_line='1';; # }}}
+  pane) # {{{
+    local ppid=$(tmux display-message -t $pane -p -F '#{pane_pid}')
+    if ! $IS_MAC; then
+      command pstree -Ac $ppid | command grep -q -e '---vim'
+    else
+      command pstree $ppid | command grep -q -i -e 'vim'
+    fi || { echo "Vim not found in pane '$pane'" >/dev/stderr; sleep 1; return 0; };; # }}}
+  *) # {{{
+    { echo "Unknown command [$cmd]" >/dev/stderr; sleep 1; return 0; };; # }}}
   esac # }}}
   case $cmd in # {{{
-  prev) [[ -h $file ]] && echo -e "File ${file##*/} links to $(readlink $file)\n" && file="$(readlink -f $file)"
-        if [[ -f $file ]]; then
-          local t="$(file --mime $file)"
-          [[ "$t" =~ binary ]] && echo "$file is a binary" && return 0
-          if which highlight >/dev/null 2>&1; then
-            [[ ${file##*/} != *.* && ( "$t" =~ shellscript || "$t" =~ text/plain ) ]] && t="-S bash" || t=""
-            highlight -O ansi $t $file 2>/dev/null || cat $file
-          else
-            cat $file
-          fi | cat -n - | cut -c3- | tail -n+$first_line | head -n $prev_lines_cnt | $ALIASES hl +cY "^\s*$line\s"
-        elif [[ -d $file ]]; then
-          ! which tree >/dev/null 2>&1 && echo "$file is a directory" && return 0
-          tree -C $file 2>/dev/null | head -200
-        else
-          echo "Not supported entity [$file]"
-        fi;;
-  pane) [[ $file != /* ]] && file="$PWD/$file"
-        tmux send-keys -t $pane ":call RelTabEdit(\"$file\")"
-        if [[ ! -z $line ]]; then
-          tmux send-keys -t $pane "zR${line}gg"
-        fi;;
-  *)    $cmd $params </dev/tty >/dev/tty;;
+  prev) # {{{
+    [[ -h $file ]] && echo -e "File ${file##*/} links to $(readlink $file)\n" && file="$(readlink -f $file)"
+    if [[ -f $file ]]; then
+      local t="$(file --mime $file)"
+      [[ "$t" =~ binary ]] && echo "$file is a binary" && return 0
+      if which highlight >/dev/null 2>&1; then
+        [[ ${file##*/} != *.* && ( "$t" =~ shellscript || "$t" =~ text/plain ) ]] && t="-S bash" || t=""
+        highlight -O ansi $t $file 2>/dev/null || cat $file
+      else
+        cat $file
+      fi | cat -n - | cut -c3- | tail -n+$first_line | head -n $prev_lines_cnt | hl +cY "^\s*$line\s"
+    elif [[ -d $file ]]; then
+      ! which tree >/dev/null 2>&1 && echo "$file is a directory" && return 0
+      tree -C $file 2>/dev/null | head -200
+    else
+      echo "Not supported entity [$file]"
+    fi;; # }}}
+  pane) # {{{
+    [[ $file != /* ]] && file="$PWD/$file"
+    if isInstalled realpath; then
+      local paneCwd="$(tmux display-message -p -t $pane -F '#{pane_current_path}')"
+      file="$(realpath --relative-to "$paneCwd" "$file")"
+    fi
+    tmux send-keys -t $pane ":call RelTabEdit(\"$file\")"
+    if [[ ! -z $line ]]; then
+      tmux send-keys -t $pane "zR${line}gg"
+    fi;; # }}}
+  *) # {{{
+    $cmd $params </dev/tty >/dev/tty;; # }}}
   esac # }}}
 } # }}}
 fzfwr() { # {{{
   local isInputRc=false
   [[ $1 == 'iRC' ]] && isInputRc=true && shift
-  local FZF_DEFAULT_COMMAND="fdfind" # -I"
-  if ! which ${FZF_DEFAULT_COMMAND% *} >/dev/null 2>&1; then
-    FZF_DEFAULT_COMMAND="command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2>/dev/null | cut -b3-"
+  local cmd="fdfind -d ${FZF_MAX_DEPTH:-8}"
+  if ! which ${cmd%% *} >/dev/null 2>&1; then
+    cmd="command find -L . -mindepth 1 -maxdepth 8 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2>/dev/null | cut -b3-"
   fi
-  FZF_DEFAULT_COMMAND+=" | sort"
-  local selected="$(fzf --height 80% "$@" | sed 's/^\|$/"/g' | tr '\n' ' ' | sed 's/ \+/ /')"
+  cmd+=" | sort"
+  local selected="$(__fzf_select__  --cmd "$cmd" "$@")" # | sed 's/^\|$/"/g' | tr '\n' ' ' | sed 's/ \+/ /')"
   if $isInputRc; then
     READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
     READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
@@ -202,9 +212,9 @@ vimg() { # {{{
 } # }}}
 vims() { # @@ # {{{
   if [[ $1 == '@@' ]]; then # {{{
-    case $2 in
-    1) $ALIASES fzf_exe @@ - --pane;;
-    *) echo "@@-f";;
+    case $3 in
+    -t) fzf_exe @@ - --pane;;
+    *)  echo "@@-f -t -v";;
     esac
     return 0
   fi # }}}
@@ -228,9 +238,13 @@ vims() { # @@ # {{{
     done
   } # }}}
   local dst='.1' f= verb=false
-  [[ $1 == '-v' ]] && verb=true && shift
-  [[ $# -ge 2 ]] && dst="$1" && shift
-  f="$@"
+  while [[ ! -z $1 ]]; do
+    case $1 in
+    -v) verb=true;;
+    -t) dst="$2"; shift;;
+    *)  f="$@"; shift $#;;
+    esac; shift
+  done
   [[ $dst =~ .*\..* ]] || dst+=".1"
   if [[ ! -t 0 ]]; then
     f="$(cat - | xargs -n1 | __vims__find_files | fzf)"
@@ -240,7 +254,7 @@ vims() { # @@ # {{{
   [[ $? != 0 || -z $f ]] && return 0
   for i in $f; do
     if [[ -e "$i" ]]; then
-      $ALIASES fzf_exe -c pane --pane $dst -f "$i"
+      fzf_exe -c pane --pane $dst -f "$i"
     elif $verb; then
       echo "File [$f] does not exist" >/dev/stderr
     fi
diff --git a/bash/aliases.d/reminder b/bash/aliases.d/reminder
--- a/bash/aliases.d/reminder
+++ b/bash/aliases.d/reminder
@@ -2,9 +2,8 @@
 # vim: fdl=0
 
 reminder() { # @@ # {{{
-  local i= tool='/usr/bin/notify-send' verbose=">/dev/null 2>&1" be_verbose=false silent=false
   if [[ $1 == @@ ]]; then # {{{
-    local ret="-v -i -rm -l --list"
+    local ret="-v -i -rm -l --list -l-full --list-full -e --edit --no-at"
     case $3 in
     -i | -rm) # {{{
       ret="$(at -l | awk '{print $1}')" ;; # }}}
@@ -25,24 +24,33 @@ reminder() { # @@ # {{{
     return 0
   fi # }}}
   $IS_MAC && tool="$BASH_PATH/messages.sh"
-  type $tool >/dev/null 2>&1 || { ! $silent && echo "Notifier tool [$tool] not found" >/dev/stderr; return 1; }
-  [[ -z $1 || ! -t 1 ]] && set -- -l
+  type $tool >/dev/null 2>&1 || $silent || { echor "Notifier tool [$tool] not found"; return 1; }
+  local i= j= no= tool='/usr/bin/notify-send' verbose=">/dev/null 2>&1" be_verbose=false silent=false addAtP=true pd= pt=
+  while [[ ! -z $1 ]]; do # {{{
+    case $1 in
+    -v) verbose=; be_verbose=true;;
+    -s) silent=true;;
+    *)  break;;
+    esac; shift
+  done # }}}
+  if [[ -z $1 ]]; then
+    [[ -t 1 ]] && set -- -e || set -- -l
+  fi
   while [[ ! -z $1 ]]; do # {{{
     case $1 in
     -i) # {{{
-      local no="$2"
-      if [[ -z $no ]]; then # {{{
-        for no in $(at -l | sort -k1,1n | awk '{print $1}'); do
-          reminder -i $no
-        done
-        return 0
-      fi # }}}
-      ! at -l | command grep -q "^$no\s" && return 1
-      at -l | command grep "^$no\s"
-      at -c "$no" | sed -e '1,/exit 1/ d' -e '/^[{}]/d' -e '/^\s*$/d' | sed 's/^/\t/'
+      shift
+      for i in ${@:-$(at -l | sort -k1,1n | awk '{print $1}')}; do
+        at -l | command grep -q "^$i\s" || continue
+        at -l | command grep "^$i\s"
+        at -c "$i" | sed -e '1,/exit 1/ d' -e '/^[{}]/d' -e '/^\s*$/d' | sed 's/^/\t/'
+      done
       return 0;; # }}}
-    -l | --list | -rm) # {{{
-      local oIFS="$IFS" list= no= d= msg= i=
+    -e      | --edit | \
+    -rm     | \
+    -l      | --list | \
+    -l-full | --list-full) # {{{
+      local oIFS="$IFS" list= d= msg=
       IFS=
       while read i; do # {{{
         no="$(echo "$i" | awk '{print $1}')"
@@ -51,23 +59,126 @@ reminder() { # @@ # {{{
         list+="$no $d : $msg\n"
       done < <(at -l) # }}}
       IFS="$oIFS"
-      list="$(echo -en "$list" | sort -k2,2n | sed 's/^\([0-9]\+\) \([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\) : /\1 \4.\3.\2-\5:\6 : /')"
-      ;;& # }}}
-    -l | --list) # {{{
-      echo "$list"
-      return 0;; # }}}
-    -rm) # {{{
-      shift
-      local no="$@"
-      if [[ -z $no ]]; then # {{{
-        [[ -z $list ]] && echo "Nothing to remove" >/dev/stderr && return 0
-        no="$(echo "$list" | fzf -0 -m -s --prompt 'To remove> ' | cut -d' ' -f1)"
-        [[ -z $no ]] && return
-      fi # }}}
-      at -r $no
+      list="$(echo -en "$list" \
+        | sort -k2,2n \
+        | sed 's/^\([0-9]\+\) \([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\) : /\1 \4.\3.\2-\5:\6 : /' \
+        | sed -e 's| --at=[0-9]\+||')"
+      case $1 in
+      -e      | --edit) # {{{
+        list="$(echo -en "$list" \
+          | sed -e 's|/[^ ]*/||' -e 's|ll-||' -e 's|\.sh||' \
+          | sed -e 's|pni|@|' -e 's|go-home|GH|' -e 's|pause|P|' -e 's|notify-send .* Reminder:|!|' \
+          | sed -e 's|^\([0-9]\+\) \([0-9.]\+\)-\([0-9:]\+\) : |\1 \2 \3 |' \
+        )"
+        declare -a listC listIds listN toAdd toRemove
+        readarray -t listC <<<$(echo "$list" | sed 's/^[0-9]* \+//')
+        readarray -t listIds <<<$(echo "$list" | sed 's/ .*//')
+        local tmpFile=$TMP_MEM_PATH/reminder.$$.tmp # {{{
+        (
+          for i in ${!listC[*]}; do echo "${listC[i]}"; done
+          echo
+          echo "# Usage: time-stamp P|@|!|GH msg"
+          echo "#"
+          echo "# P  :: pause   :: P msg"
+          echo "# @  :: pni     :: @ msg(@time)"
+          echo "# !  :: notif   :: ! msg"
+          echo "# GH :: go-home :: GH msg"
+        ) >$tmpFile # }}}
+        vim --fast-save -1l $tmpFile || { rm $tmpFile; return 0; }
+        readarray -t listN <<<$(cat $tmpFile | sed -e '/^#/d' -e '/^\s*$/d')
+        rm $tmpFile
+        for i in ${!listN[*]}; do # {{{
+          for j in ${!listC[*]}; do
+            [[ ${listN[i]} == ${listC[j]} ]] || continue
+            listC[j]=""
+            continue 2
+          done
+          toAdd+=("${listN[i]}")
+        done # }}}
+        for i in ${!listC[*]}; do # {{{
+          [[ -z ${listC[i]} ]] && continue
+          toRemove+=("${listIds[i]}")
+        done # }}}
+        [[ ! -z ${toAdd[*]} || ! -z ${toRemove[*]} ]] || return 0
+        for i in ${!toAdd[*]}; do # {{{
+          line=${toAdd[i]}
+          local newTs= newWhat= newMsg=
+          if [[ $line =~ ^([0-9.: -]+)\ +(P|@|!|GH|p|gh)?(\ *(.*))? ]]; then # {{{
+            newTs="$(echo ${BASH_REMATCH[1]})"
+            newWhat="$(echo ${BASH_REMATCH[2]})"
+            newMsg="$(echo ${BASH_REMATCH[4]})"
+            [[ $newTs == *' :' ]] && newTs=${newTs% :}
+            newTs="$(echo $newTs)"
+          else
+            { $silent || echor "Ignored line: [$line]"; } && continue
+          fi # }}}
+          case ${newWhat^^} in # {{{
+          P)  newWhat="pause.sh";;
+          GH) newWhat="go-home.sh";;
+          @)  newWhat="ll-pni.sh";;
+          \!) newWhat="";;
+          '') newWhat="";;
+          esac # }}}
+          if [[ " $newTs " =~ [0-9.-]+[\ -]([0-9][0-9]?:[0-9][0-9]?) ]]; then
+            pt=${BASH_REMATCH[1]} && pd="$(echo ${newTs/$pt})" && pd=${pd%-}
+          elif [[ " $newTs " =~ ([0-9][0-9]?:[0-9][0-9]?) ]]; then
+            pt=$newTs
+          else
+            { $silent || echor "cannot parse TS: [$newTs]"; } && continue
+          fi
+          if [[ ! -z $pd ]]; then
+            pd=${pd%.}
+            [[ $pd =~ ^([0-9][0-9]?)$ ]] && pd+=".$(command date +%m)"
+            [[ $pd =~ ^([0-9][0-9]?)\.([0-9][0-9]?)$ ]] && pd+=".$(command date +%y)"
+            [[ $pd =~ ^([0-9][0-9]?)\.([0-9][0-9]?)\.([0-9][0-9])$ ]] && pd=${BASH_REMATCH[3]}-${BASH_REMATCH[2]}-${BASH_REMATCH[1]}
+          fi
+          reminder -s $newWhat $([[ ! -z $newMsg ]] && echo "'$newMsg'") "$pt $pd" || $silent || echor "Failed to add [$newWhat] at [$pt $pd]"
+        done # }}}
+        for i in ${!toRemove[*]}; do # {{{
+          at -r ${toRemove[i]}
+        done # }}}
+        $silent || reminder -l;; # }}}
+      -rm     | \
+      -l      | --list | \
+      -l-full | --list-full) # {{{
+        [[ -z $list ]] && return 0
+        local id= ts= tmp= rest= isFull=false
+        local today="$(command date +%d.%m.%y)"
+        [[ $1 == '-l-full' || $1 == '--list-full' ]] && isFull=true
+        echo "$list" | while read id ts tmp rest; do # {{{
+          case $rest in
+          */pause.sh*)        rest="P ${rest#*/pause.sh}";;
+          */go-home.sh*)      rest="GH ${rest#*/go-home.sh}";;
+          */reminders/*.sh*)  rest="${rest#*/reminders/}";;
+          *\ Reminder:\ -*)   rest="- ${rest#* Reminder: -}";;
+          *\ Reminder:\ *)    rest="! ${rest#* Reminder: }";;
+          */ll-pni.sh*)       rest="@ ${rest#*/ll-pni.sh}";;
+          */ll-*)             rest="LL-${rest#*/ll-}";;
+          /*)                 rest="C ${rest##*/}";;
+          esac
+          rest="$(echo $rest | sed -e 's|/[^ ]*/||' -e 's|\.sh||')"
+          if $isFull; then
+            echo "${ts/-/ }: $rest"
+          else
+            [[ $ts == $today* ]] || continue
+            echo "${ts#*-}: $rest"
+          fi
+        done # }}}
+        case $1 in
+        -rm) # {{{
+          shift
+          local no="$@"
+          if [[ -z $no ]]; then # {{{
+            no="$(echo "$list" | fzf -0 -m -s --prompt 'To remove> ' | cut -d' ' -f1)"
+            [[ -z $no ]] && return
+          fi # }}}
+          at -r $no;; # }}}
+        esac;; # }}}
+      esac
       return 0;; # }}}
     -v) verbose=; be_verbose=true;;
     -s) silent=true;;
+    --no-at) addAtP=false;;
     *)  break;;
     esac
     shift
@@ -77,21 +188,30 @@ reminder() { # @@ # {{{
     ts="${@:$#:$#}"
     params="${@:2:$#-2}"
   fi
-  [[ ! -z $msg && ! -z $ts ]] || { ! $silent && echo "Argument missing [$@]" >/dev/stderr; return 1; }
-  [[ ! -z "$REMINDER_DIR" && -e "$REMINDER_DIR/$msg" ]] && msg="$REMINDER_DIR/$msg"
+  [[ ! -z $msg && ! -z $ts ]] || $silent || { echor "Argument missing [$@]"; return 1; }
+  time2s --is-hms "$ts" && ts="$(time2s $ts)"
+  [[ " $ts " =~ .*\ ([0-9][0-9]?:[0-9][0-9]?(:[0-9][0-9]?)?)\ .* ]] && pt=${BASH_REMATCH[1]} && pd="$(echo ${ts/$pt})"
+  if [[ ! -z $pd ]]; then
+    pd=${pd%.}
+    [[ $pd =~ ^([0-9][0-9]?)$ ]] && pd+=".$(command date +%m)"
+    [[ $pd =~ ^([0-9][0-9]?)\.([0-9][0-9]?)$ ]] && pd+=".$(command date +%y)"
+    [[ $pd =~ ^([0-9][0-9]?)\.([0-9][0-9]?)\.([0-9][0-9])$ ]] && pd=${BASH_REMATCH[3]}-${BASH_REMATCH[2]}-${BASH_REMATCH[1]}
+  fi
+  [[ "$pt" == *:*:* ]] && pt="${pt%:*}"
+  local tsAbs="$(time2s "$pd $pt" -o abs-s)"
+  if [[ "$tsAbs" -le $((EPOCHSECONDS + 30)) ]]; then
+    $silent || echor "Scheduled time is before near-now, rejecting"
+    return 1
+  fi
+  if [[ ! -z "$REMINDER_DIR" && -e "$REMINDER_DIR/$msg" ]]; then
+    msg="$REMINDER_DIR/$msg"
+    $addAtP && params="--at=$tsAbs $params"
+  fi
   [[ "$msg" == ./* ]] && msg="$PWD/$msg"
   [[ "$msg" == /* && -e "$msg" ]] && file=true
-  ts="$($ALIASES time2s "$ts")"
-  [[ $? == 0 && $ts == *:*:* ]] && ts="${ts%:*}"
-  if [[ $ts =~ ^[0-9]+:[0-9]+$ ]]; then
-    if [[ $((10#${ts//:})) -le "$((10#$(command date +'%H%M')))" ]]; then
-      ! $silent && echo "Scheduled time is before now, rejecting" >/dev/stderr
-      return 1
-    fi
-  fi
   if $file; then # {{{
     $be_verbose && set -xv
-    echo "$msg $params" | ( command cd $HOME; eval at "'$ts'" $verbose )
+    echo "$msg $params" | ( command cd $HOME; eval at "'$pt $pd'" $verbose )
     err="$?"
     $be_verbose && set +xv
     ! command grep -q "${tool##*/}\|no-notify" "$msg" && msg="Script [${msg##*/}] executed" && file=false
@@ -106,7 +226,7 @@ reminder() { # @@ # {{{
       else
         echo "$tool 'Reminder' '$msg'"
       fi
-    fi | ( $be_verbose && set -xv; command cd $HOME; eval at "'$ts'" $verbose )
+    fi | ( $be_verbose && set -xv; command cd $HOME; eval at "'$pt $pd'" $verbose )
     err="$?"
   fi # }}}
   if [[ $err == 0 ]]; then
@@ -115,7 +235,7 @@ reminder() { # @@ # {{{
       at -c "$(at -l | sort -k1,1n | tail -n1 | awk '{print $1}')" | sed -n -e '/^\s*$/d' -e '/^\/home/,$ p' | sed 's/^/\t/'
     fi
   else
-    ! $silent && echo "Failed to schedule the reminder" >/dev/stderr
+    $silent || echor "Failed to schedule the reminder"
   fi
   return $err
 } # }}}
diff --git a/bash/colors b/bash/colors
--- a/bash/colors
+++ b/bash/colors
@@ -1,23 +1,79 @@
 # vim: filetype=sh fdl=0
 
 # Is installed # {{{
-if [[ $1 == '--list' ]]; then
-  awk -F'[= ]' '/^export +C[A-Z]/ && !/# IGN/ {print $2}' $0 | sort -u
+[[ -z $1 && ! -z $BASHRC_PARAMS_COLORS ]] && set -- $BASHRC_PARAMS_COLORS
+if [[ $1 == '--list' ]]; then # {{{
+  awk -F'=' '/^ *export C[A-Z]/ && !/# IGN/ {print $1}' $0 | sed 's/.*export //' | sort -u
   exit 0
-fi
-${RCSTUFF_COLORS_INSTALLED:-false} && [[ $1 != '--force' ]] && [[ ! -z ${COff} ]] && return 0
+fi # }}}
+${RCSTUFF_COLORS_INSTALLED:-false} && [[ $1 != '--force' ]] && ! ${RCSTUFF_FORCE:-false} && [[ ! -z ${COff} ]] && return 0
 export RCSTUFF_COLORS_INSTALLED=true
 # }}}
 # Env # {{{
-export COLORS_BASIC_LIST="CGreen black red green yellow blue purple cyan white search HLSearch GoldOrig gold gray off CIBlack CIRed CIGreen CIYellow CIBlue CIPurple CICyan CIWhite " # IGN
-declare -A -x COLORS
-COLORS+=([err]="red" [ok]="green" [info]="yellow" [i2]="cyan"); COLORS[i1]=${COLORS[info]}
-COLORS+=([imp]="HLSearch" [imp2]="Gold")
-COLORS+=([ip]="yellow")
-export COLORS_FILE="$TMP_MEM_PATH/.colors" # IGN
-[[ $1 == '--force' ]] && shift && rm -f $COLORS_FILE
+export COLORS_BASIC_LIST="" # IGN
+export COLORS_BASIC_LIST+=" black   red   green   yellow   blue   purple   cyan   white  gold  gray  off"   # IGN
+export COLORS_BASIC_LIST+=" CBlack  CRed  CGreen  CYellow  CBlue  CPurple  CCyan  CWhite CGold CGray COff"  # IGN
+export COLORS_BASIC_LIST+=" CIBlack CIRed CIGreen CIYellow CIBlue CIPurple CICyan CIWhite"                  # IGN
+export COLORS_BASIC_LIST+=" HLSearch GoldOrig"                                                              # IGN
+export COLORS_FILE="$BASHRC_RUNTIME_PATH/colors" # IGN
+if [[ $1 == '--force' ]] || ${RCSTUFF_FORCE:-false}; then # {{{
+  [[ $1 == '--force' ]] && shift
+  rm -f $COLORS_FILE
+  unset colorCache
+fi # }}}
+if [[ -e $COLORS_FILE ]]; then
+  source $COLORS_FILE
+else
+  declare -A -x colorCache=([off]="$COff")
+  declare -A -x COLORS
+  COLORS+=([err]="red" [ok]="green" [wrn]="purple" [info]="yellow" [i2]="cyan"); COLORS[i1]=${COLORS[info]}
+  COLORS+=([imp]="HLSearch" [imp2]="Gold")
+  COLORS[ip]="yellow"
+  COLORS[ts]="blue"
+  COLORS[file]="cyan"
+  COLORS[ticket]="cyan"
+  COLORS[grey]="gray"
+fi
 # }}}
-colorsInit() { # {{{
+colorCacheDump() { # {{{
+  [[ -e $COLORS_FILE ]] || colorCacheInit -s
+  if [[ -e $COLORS_FILE ]]; then # {{{
+    source $COLORS_FILE
+  else
+    ! declare -p colorCache >/dev/null 2>&1 && declare -A -x colorCache=([off]="$COff")
+    ! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap
+    ! declare -p COLORS >/dev/null 2>&1 && declare -A -x COLORS
+  fi # }}}
+  local i= w1=9 w2=-12 colors_ci= cOff="$(getColor --cached off)"
+  echor -C "%yellow:{colorCache}:"
+  for i in $(echo "${!colorCache[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
+    if [[ $i =~ ^CI[A-Z] ]]; then
+      colors_ci+="$i "
+      continue
+    fi
+    if [[ $i =~ ^C[A-Z] ]]; then
+      echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "$i") --"
+    else
+      if [[ ! -z $colors_ci ]]; then
+        local ii=
+        for ii in $colors_ci; do
+          echor "  $(printf "%${w1}s" "$ii") : -- $(printf "$(getColor --cached $ii)%${w2}s$cOff" "$ii") --"
+        done
+        colors_ci=
+      fi
+      echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "$i") --"
+    fi
+  done
+  echor -C "%yellow:{COLORS}:"
+  for i in $(echo "${!COLORS[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
+    echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "${COLORS[$i]}") --"
+  done
+  echor -C "%yellow:{colorsMap}:"
+  for i in $(echo "${!colorsMap[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
+    echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "${COLORS[$i]}") --"
+  done
+} # }}}
+colorCacheInit() { # {{{
   local i= k= verbose=false addSource=true
   while [[ ! -z $1 ]]; do
     case $1 in
@@ -28,7 +84,7 @@ colorsInit() { # {{{
   for i in off $COLORS_BASIC_LIST ${!COLORS[*]} $@; do
     [[ $i =~ ^[A-Za-z] ]] || continue
     if $verbose; then
-      echo "$(getColor $i)Storing${COff}: $i"
+      echo "$(getColor --cache $i)Storing1${COff}: $i"
     else
       getColor $i >/dev/null
     fi
@@ -37,66 +93,93 @@ colorsInit() { # {{{
     i=${COLORS[$i]}
     [[ $i =~ ^[A-Za-z] ]] || continue
     if $verbose; then
-      echo "$(getColor $i)Storing${COff}: $i"
+      echo "$(getColor --cache $i)Storing2${COff}: $i"
     else
       getColor $i >/dev/null
     fi
   done
   if $addSource && [[ -e $COLORS_FILE ]]; then
-    echo "source $COLORS_FILE # for eval"
+    source $COLORS_FILE
   fi
 }
-export -f colorsInit
-# }}}
-getColorList() { # {{{
-  if [[ $1 == '@@' ]]; then
-    echo "--raw -I --full"
-    return 0
+export -f colorCacheInit # }}}
+colorList() { # {{{
+  local list=
+  if [[ $1 == '--full' ]]; then
+    list="$(awk -F'=' '/^ *export C[A-Z]/ && !/# IGN/ {print $1}'  $BASH_PATH/colors | sed 's/.*export //' | sort -u)"
   fi
-  local list="$(awk -F'[= ]' '/^export +C[A-Z]/ && !/# IGN/ {print $2}' $BASH_PATH/colors)"
-  case $1 in
-  --raw) echo "$list";;
-  *)
-    list="$(echo "$list" | sed 's/^C//')"
-    case $1 in
-    -I)     echo "$list";;
-    --full | --compl)
-      if [[ $1 == '--compl' ]]; then
-        echo "$list" | sed 's/^[A-Z][a-z]*$/\L\0/' # | sed 's/^[a-z].*/'${CGreen}'\0'${COff}'/'
-      else
-        echo "$list" | sed 's/^[A-Z][a-z]*$/\L\0/'
-      fi;;
-    *)      echo "$list" | sed -n 's/^[A-Z][a-z]*$/\L\0/p'; echo -e "HLSearch\nGoldOrig";;
-    esac
-  esac | sort -u
-}
-complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic getColorList
-export -f getColorList # }}}
+  (
+    if [[ -e $COLORS_FILE ]]; then # {{{
+      source $COLORS_FILE
+    else
+      ! declare -p colorCache >/dev/null 2>&1 && declare -A -x colorCache=([off]="$COff")
+      ! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap
+      ! declare -p COLORS >/dev/null 2>&1 && declare -A -x COLORS
+    fi # }}}
+    (
+      echo "$COLORS_BASIC_LIST"
+    ) | tr ' ' '\n' | sed '/^C[A-Z][a-z]/s/^C\(.*\)/\L\1/'
+    echo "${!COLORS[*]}"
+    echo "${!colorsMap[*]}"
+    echo "${!colorCache[*]}"
+    echo "$list"
+  ) | tr ' ' '\n' | sed '/^ *$/d' | LC_COLLATE=C sort -u
+} # }}}
 getColor() { # {{{
   if [[ $1 == '@@' ]]; then # {{{
     case $3 in
     -c | --color) # {{{
-      echo "${!colors[*]}" # aim: local, per-tool array
-      echo "${!COLORS[*]}" # aim: global, common array
-      getColorList --compl
-      ;; # }}}
+      colorList --full;; # }}}
+    -f | -b) # {{{
+      seq 0 255;; # }}}
+    -r | --raw) # {{{
+      echo "-f -b -n --name FG-space-BG";; # }}}
     *) # {{{
-      echo "-c --color"
-      echo "${!colors[*]}" # aim: local, per-tool array
-      echo "${!COLORS[*]}" # aim: global, common array
-      getColorList;; # }}}
+      echo "-c --color -r --raw"
+      colorList;; # }}}
     esac
     return 0
   fi # }}}
   [[ $colorsOn == false || $COLORS_ON == false ]] && return 0
-  ! declare -p colors >/dev/null 2>&1 && declare -A -x colors
-  if [[ -z "${colorCache[off]}" ]]; then
-    [[ -e $COLORS_FILE ]] && source $COLORS_FILE || declare -A -x colorCache
-  fi
+  if [[ $1 == --cached ]]; then # {{{
+    shift
+  else
+    if [[ -e $COLORS_FILE ]]; then # {{{
+      source $COLORS_FILE
+    else
+      ! declare -p colorCache >/dev/null 2>&1 && declare -A -x colorCache=([off]="$COff")
+      ! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap
+      ! declare -p COLORS >/dev/null 2>&1 && declare -A -x COLORS
+    fi # }}}
+  fi # }}}
   local name="$1" c=
-  [[ $name == '-c' || $name == '--color' ]] && shift && name="$1"
-  if [[ ! -z ${colors[$name]} ]]; then
-    c=${colors[$name]}
+  case $name in
+  -r | --raw) # {{{
+    shift
+    local cFg=15 cBg=0 name=
+    while [[ ! -z $1 ]]; do
+      case $1 in
+      -f) cFg=$2;;
+      -b) cBg=$2;;
+      -n | --name) name="$2"; shift;;
+      *) cFg=$1; cBg=$2; [[ -z $name ]] && name="$3"; shift $#;;
+      esac; shift
+    done
+    cFg="$(printf "%03d" "$cFg")"
+    cBg="$(printf "%03d" "$cBg")"
+    [[ -z $name ]] && name="rF${cFg}B${cBg}"
+    local c="${colorCache[$name]}"
+    [[ ! -z $c ]] && echo "$c" && return 0
+    c="$(printf "\x1b%s\x1b%s" "[38;5;${cFg}m" "[48;5;${cBg}m")"
+    colorCache[$name]="$c"
+    [[ -e $COLORS_FILE ]] && sed -i '/colorCache/d' $COLORS_FILE
+    declare -p colorCache >>$COLORS_FILE
+    echo "$c"
+    return 0;; # }}}
+  -c | --color) shift; name="$1";;
+  esac
+  if [[ ! -z ${colorsMap[$name]} ]]; then
+    c=${colorsMap[$name]}
   elif [[ ! -z ${COLORS[$name]} ]]; then
     c=${COLORS[$name]}
   fi
@@ -113,40 +196,42 @@ getColor() { # {{{
   [[ -z $c ]] && return 1
   if [[ $name =~ ^[A-Za-z] ]]; then
     colorCache[$name]="$c"
-    sed -i '/colorCache/d' $COLORS_FILE
+    [[ -e $COLORS_FILE ]] && sed -i '/colorCache/d' $COLORS_FILE
     declare -p colorCache >>$COLORS_FILE
   fi
   echo "$c"
 }
-complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic getColor
-export -f getColor # }}}
+export -f getColor
+complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic getColor # }}}
 cl() { # {{{
   if [[ $1 == '@@' ]]; then # {{{
-    echo "${!colors[*]}" # aim: local, per-tool array
-    echo "${!COLORS[*]}" # aim: global, common array
-    getColorList
-    if [[ $1 != '-C' ]]; then
-      echo "- -- -C -f -F Color Str"
+    colorList
+    if [[ $3 != '-C' ]]; then
+      echo "- -- -C -f -F COLOR-space-STR COLOR:STR(space-added) COLOR::STR(no-space-added) --sep"
     fi
     return 0
   fi # }}}
-  if [[ $colorsOn == false || $COLORS_ON == false ]]; then
-    declare -A -x colorCache
-  elif [[ -z "${colorCache[off]}" ]]; then
-    [[ -e $COLORS_FILE ]] && source $COLORS_FILE || declare -A -x colorCache
-  fi
-  local coff=${colorCache[off]} cCurrent= verbose=false format=false asArray=false
-  [[ -z $coff ]] && coff=$(getColor off)
+  if [[ $colorsOn != false && $COLORS_ON != false ]]; then # {{{
+    if [[ -e $COLORS_FILE ]]; then # {{{
+      source $COLORS_FILE
+    else
+      ! declare -p colorCache >/dev/null 2>&1 && declare -A -x colorCache
+      ! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap
+      ! declare -p COLORS >/dev/null 2>&1 && declare -A -x COLORS
+    fi # }}}
+  fi # }}}
+  local coff=${colorCache[off]} cCurrent= verbose=false format=false asArray=false sep=" "
+  [[ -z $coff ]] && coff=$(getColor --cached off)
   while [[ ! -z $1 ]]; do # {{{
     case $1 in
     -v) verbose=true;;
     -f) format=true;;
     -F) format=true; asArray=true;;
+    --sep) sep="$2"; shift;;
     -C) # {{{
       shift
-      cCurrent=$(getColor ${1%%:*}) || { $verbose && echo "Cannot find color for '$1'" >/dev/stderr; }
-      $format && shift
-      break;; # }}}
+      cCurrent=$(getColor --cached ${1%%:*}) || { $verbose && echo "Cannot find color for '${1%%:*}'" >/dev/stderr; }
+      ! $format && [[ $1 == *:* ]] && break;; # }}}
     *) break;;
     esac; shift
   done # }}}
@@ -156,33 +241,37 @@ cl() { # {{{
   if $format; then # {{{
     local str=
     if $asArray; then # {{{
-      local inS=() c= cc=
-      read -a inS <<<"$1"; shift
-      for i in ${!inS[*]}; do # {{{
-        str="${inS[$i]}"
-        if [[ "$str" == *%*:* && "$str" =~ (.*)%([a-zA-Z][a-zA-Z0-9_-]*):(.*) ]]; then # Use pre-check based on wildcard for speed-up # {{{
-          local pre=${BASH_REMATCH[1]} substr="${BASH_REMATCH[3]}" rest=
-          if [[ "$substr" == '{'*'}'* ]]; then
-            rest="${substr#*\}}"
-            substr="${substr%%\}*}" && substr="${substr#\{}"
-          elif [[ "$substr" == '%s'* ]]; then
-            rest="${substr#\%s}"
-            substr="$1"; shift
-          fi
-          c="${BASH_REMATCH[2]}"
-          str="$pre$(cl $c "$substr")$cCurrent$rest"
-          # }}}
-        elif [[ "$str" == *:%s && "$str" =~ [^a-zA-Z]*([a-zA-Z][a-zA-Z0-9_-]*):%s ]]; then # Use pre-check based on wildcard for speed-up # {{{
-          c="${BASH_REMATCH[1]}"
-          cc="$(cl $c $1)"; shift
-          str="${str/$c:\%s/$cc}" # }}}
-        elif [[ $str == *"%s"* ]]; then # {{{
-          cc=$(cl $1 $2); shift; shift
-          str="${str/\%s/$cc}"
-        elif [[ ! -z $cCurrent ]]; then
-          str="$cCurrent$str"
-        fi # }}}
-        [[ ! -z "$out" ]] && str=" $str"
+      local c= cc=
+      mapfile -d' ' < <(echo -n "$1"); shift
+      for i in ${!MAPFILE[*]}; do # {{{
+        str="${MAPFILE[$i]}"
+        [[ $str == " " ]] && out+="$sep" && continue
+        if [[ $str != *%%* ]]; then
+          if [[ "$str" == *%*:* && "$str" =~ (.*)%([a-zA-Z][a-zA-Z0-9_-]*):(.*) ]]; then # Use pre-check based on wildcard for speed-up # {{{
+            local pre=${BASH_REMATCH[1]} substr="${BASH_REMATCH[3]}" rest=
+            if [[ "$substr" == '{'*'}'* ]]; then
+              rest="${substr#*\}}"
+              substr="${substr%%\}*}" && substr="${substr#\{}"
+            elif [[ "$substr" == '%s'* ]]; then
+              rest="${substr#\%s}"
+              substr="$1"; shift
+            fi
+            c="${BASH_REMATCH[2]}"
+            str="$pre$(cl $c "$substr")$cCurrent$rest"
+            # }}}
+          elif [[ "$str" == *:%s && "$str" =~ [^a-zA-Z]*([a-zA-Z][a-zA-Z0-9_-]*):%s ]]; then # Use pre-check based on wildcard for speed-up # {{{
+            c="${BASH_REMATCH[1]}"
+            cc="$(cl $c $1)"; shift
+            str="${str/$c:\%s/$cc}" # }}}
+          elif [[ $str == *"%s"* ]]; then # {{{
+            cc=$(cl $1 $2); shift; shift
+            str="${str/\%s/$cc}"
+          elif [[ ! -z $cCurrent ]]; then
+            str="$cCurrent$str"
+          fi # }}}
+        else
+          str="$(printf "${str/\%\%/\%}" "$1")"; shift
+        fi
         out+="$str"
       done # }}}
       # }}}
@@ -199,7 +288,7 @@ cl() { # {{{
     while [[ ! -z $1 ]]; do # {{{
       case $1 in
       --) # {{{
-        out+=" "; shift;; # }}}
+        out+="$sep"; shift;; # }}}
       *) # {{{
         local c= n= str=
         case $1 in
@@ -215,18 +304,18 @@ cl() { # {{{
           shift; shift;; # }}}
         esac
         [[ -z "$str" ]] && continue
+        [[ $colorsOn == false || $COLORS_ON == false ]] && out+="$str" && continue
         if [[ ! -z $n && $n != '-' ]]; then # {{{
-          if [[ -z ${colors[$n]} ]]; then
-            c="${colorCache[$n]}"
-          else
-            n=${colors[$n]}
+          if [[ ! -z ${colorsMap[$n]} ]]; then
+            n=${colorsMap[$n]}
           fi
+          c="${colorCache[$n]}"
           if [[ -z $c ]]; then
-            c=$(getColor $n) || { $verbose && echo "Cannot find color for '$n'" >/dev/stderr; }
+            c=$(getColor --cached $n) || { $verbose && echo "Cannot find color for '$n'" >/dev/stderr; }
             colorCache[$n]="$c"
           fi
           cLast=$c # }}}
-        else # {{{
+        elif [[ ! -z $cCurrent || ! -z $cLast ]]; then # {{{
           cLast=${cCurrent:-$coff}
         fi # }}}
         out+="$cLast$str"
@@ -235,18 +324,22 @@ cl() { # {{{
     done # }}}
   fi # }}}
   [[ -z $out ]] && return
-  [[ $cLast != $coff ]] && out+="$coff"
+  [[ ! -z $cLast && $cLast != $coff ]] && out+="$coff"
   echo -e "$out"
 }
 complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic cl
 printfc() { cl -F "$@"; }
 clf()     { cl -F "$@"; }
 echoc()   { cl -F "$@"; }
-export -f cl clf printfc echoc # }}}
-# Reset {{{
-export COff='[0m'
 # }}}
-# Regular Colors {{{
+# Reset # {{{
+export COff='[0m'
+export CBold='[1m'
+export CItalic='[3m'
+export CUnderline='[4m'
+export CStrike='[9m'
+# }}}
+# Regular Colors # {{{
 export CBlack='[0;30m'
 export CRed='[0;31m'
 export CGreen='[0;32m'
@@ -296,85 +389,83 @@ if [[ $TERM_ORIG == 'linux' ]]; then # {{{
   export CBIBlue="$CBlue"
   export CBIPurple="$CPurple"
   export CBICyan="$CCyan"
-  export CBIWhite="$CWhite"
-  return
+  export CBIWhite="$CWhite" # }}}
+else # {{{
+  # 256 Colors # {{{
+  export CSearch='[38;5;214m'
+  export CHLSearch='[38;5;208m'
+  export CGoldOrig='[38;5;220m'
+  export CGold="$CSearch"
+  export CGray='[38;5;240m'
+  # }}}
+  # Bold # {{{
+  export CBBlack='[1;30m'
+  export CBRed='[1;31m'
+  export CBGreen='[1;32m'
+  export CBYellow='[1;33m'
+  export CBBlue='[1;34m'
+  export CBPurple='[1;35m'
+  export CBCyan='[1;36m'
+  export CBWhite='[1;37m'
+  # }}}
+  # Underline # {{{
+  export CUBlack='[4;30m'
+  export CURed='[4;31m'
+  export CUGreen='[4;32m'
+  export CUYellow='[4;33m'
+  export CUBlue='[4;34m'
+  export CUPurple='[4;35m'
+  export CUCyan='[4;36m'
+  export CUWhite='[4;37m'
+  # }}}
+  # High Intensity # {{{
+  export CIBlack='[0;90m'
+  export CIRed='[0;91m'
+  export CIGreen='[0;92m'
+  export CIYellow='[0;93m'
+  export CIBlue='[0;94m'
+  export CIPurple='[0;95m'
+  export CICyan='[0;96m'
+  export CIWhite='[0;97m'
+  # }}}
+  # Bold High Intensity # {{{
+  export CBIBlack='[1;90m'
+  export CBIRed='[1;91m'
+  export CBIGreen='[1;92m'
+  export CBIYellow='[1;93m'
+  export CBIBlue='[1;94m'
+  export CBIPurple='[1;95m'
+  export CBICyan='[1;96m'
+  export CBIWhite='[1;97m'
+  # }}}
+  # Background # {{{
+  export COnBlack='[40m'
+  export COnRed='[41m'
+  export COnGreen='[42m'
+  export COnYellow='[43m'
+  export COnBlue='[44m'
+  export COnPurple='[45m'
+  export COnCyan='[46m'
+  export COnWhite='[47m'
+  # }}}
+  # High Intensity backgrounds # {{{
+  export COnIBlack='[0;100m'
+  export COnIRed='[0;101m'
+  export COnIGreen='[0;102m'
+  export COnIYellow='[0;103m'
+  export COnIBlue='[0;104m'
+  export COnIPurple='[10;95m'
+  export COnICyan='[0;106m'
+  export COnIWhite='[0;107m'
+  # }}}
 fi # }}}
-# 256 Colors {{{
-export CSearch='[38;5;214m'
-export CHLSearch='[38;5;208m'
-export CGoldOrig='[38;5;220m'
-export CGold="$CSearch"
-export CGray='[38;5;244m'
-# }}}
-# Bold {{{
-export CBBlack='[1;30m'
-export CBRed='[1;31m'
-export CBGreen='[1;32m'
-export CBYellow='[1;33m'
-export CBBlue='[1;34m'
-export CBPurple='[1;35m'
-export CBCyan='[1;36m'
-export CBWhite='[1;37m'
-# }}}
-# Underline {{{
-export CUBlack='[4;30m'
-export CURed='[4;31m'
-export CUGreen='[4;32m'
-export CUYellow='[4;33m'
-export CUBlue='[4;34m'
-export CUPurple='[4;35m'
-export CUCyan='[4;36m'
-export CUWhite='[4;37m'
-# }}}
-# High Intensity {{{
-export CIBlack='[0;90m'
-export CIRed='[0;91m'
-export CIGreen='[0;92m'
-export CIYellow='[0;93m'
-export CIBlue='[0;94m'
-export CIPurple='[0;95m'
-export CICyan='[0;96m'
-export CIWhite='[0;97m'
-# }}}
-# Bold High Intensity {{{
-export CBIBlack='[1;90m'
-export CBIRed='[1;91m'
-export CBIGreen='[1;92m'
-export CBIYellow='[1;93m'
-export CBIBlue='[1;94m'
-export CBIPurple='[1;95m'
-export CBICyan='[1;96m'
-export CBIWhite='[1;97m'
-# }}}
-# Background {{{
-export COnBlack='[40m'
-export COnRed='[41m'
-export COnGreen='[42m'
-export COnYellow='[43m'
-export COnBlue='[44m'
-export COnPurple='[45m'
-export COnCyan='[46m'
-export COnWhite='[47m'
-# }}}
-# High Intensity backgrounds {{{
-export COnIBlack='[0;100m'
-export COnIRed='[0;101m'
-export COnIGreen='[0;102m'
-export COnIYellow='[0;103m'
-export COnIBlue='[0;104m'
-export COnIPurple='[10;95m'
-export COnICyan='[0;106m'
-export COnIWhite='[0;107m'
-# }}}
 # Env, cont. # {{{
-declare -A -x colorCache
-if [[ -e $COLORS_FILE ]]; then
-  source $COLORS_FILE
-else
+if [[ ! -e $COLORS_FILE ]]; then
   touch $COLORS_FILE
   declare -p COLORS >>$COLORS_FILE
-  colorsInit -s
+  echo "! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap" >>$COLORS_FILE
+  colorCacheInit -s
 fi
-! declare -p colors >/dev/null 2>&1 && declare -A -x colors
+source $COLORS_FILE
 true
 # }}}
