S#009

diff --git a/bash/aliases.d/remember b/bash/aliases.d/remember
--- a/bash/aliases.d/remember
+++ b/bash/aliases.d/remember
@@ -2,11 +2,58 @@
 # vim: fdl=0
 
 rem() { # @@ # {{{
+  __rem-reset-conf() { # {{{
+    var= var_use_file= var_file=
+    rm -f $file
+    touch $file
+  } # }}}
+  __rem-get-item() { # {{{
+    local p= i="$1" path=
+    i="${i//	/ /}"
+    if $do_split && [[ $i == *\ * ]]; then
+      set -- $i
+      local added=false
+      for i; do
+        __rem-get-item "$i"
+        [[ $? == 0 ]] && ! $added && added=true
+      done
+      ! $added && return 1
+      return 0
+    fi
+    if $as_file; then # {{{
+      if [[ $i == '..' ]]; then
+        p="$PWD"
+      elif [[ -e $i || -h $i ]]; then
+        [[ $i == /* ]] && p="$i" || path="$PWD"
+      elif [[ ! -z $last_working_path && -e "$last_working_path/$i" ]]; then
+        path="$last_working_path"
+      else
+        local path="$PWD"
+        while [[ ! -e "$path/$i" ]]; do
+          path="$(command cd "$path/.."; pwd)"
+          [[ $path == '/' || $path == "$HOME" ]] && break
+        done
+        [[ -e "$path/$i" ]] && last_working_path="$d" || path=
+      fi
+      [[ ! -z $path ]] && p="$path/$i"
+      if ${add_not_exst:-true}; then
+        [[ -z $p ]] && p="$i"
+      elif [[ ! -e $p ]]; then
+        p=""
+      fi
+      p="${p//\/.\//\/}"
+      # }}}
+    else # {{{
+      p="$i"
+    fi # }}}
+    [[ -z $p ]] && return 1
+    var+="$p\n"
+    return 0
+  } # }}}
   # Setup # {{{
   local var="${REMEMBER_CONF_VAR:-REMEMBER}" mask_file="${REMEMBER_CONF_MASK:-remember}" store_dir="${REMEMBER_CONF_DIR:-$TMUX_RUNTIME}" \
     ls_mode="${REMEMBER_CONF_LS_MODE:-rec}" keep_n_bck_files="${REMEMBER_CONF_KEEP_N:-7}"
-  local reset_conf="echo \$var=''; echo \$var_use_file=''; echo \$var_file=''; rm -f \$file; touch \$file"
-  local var_use_file= var_file= file= i= p= fzf_prompt= cmd= tild='~'
+  local var_use_file= var_file= file= i= p= fzf_prompt= cmd=
   local do_reset=false do_use_file=true do_edit=false do_keep=true do_append=true do_fzf=false do_quiet=false do_set_store_env=false \
     do_ls=false do_list=false show_abs=false do_restore=false do_browse=false do_cmd=false as_file=true add_not_exst= do_split=false \
     do_smart= do_block_reset= line_no=
@@ -39,8 +86,8 @@ rem() { # @@ # {{{
     case $1 in
     @@ | @@@) # {{{
       case $3 in
-      --file | -f | -F) getFileList --pwd "$store_dir" "${mask_file}*.txt";;
-      --restore)        getFileList --pwd "$store_dir" "${mask_file}*.txt-*.bck";;
+      --file | -f | -F) get-file-list --pwd "$store_dir" "${mask_file}*.txt";;
+      --restore)        get-file-list --pwd "$store_dir" "${mask_file}*.txt-*.bck";;
       --ls-mode)        echo "rec rec-all 1";;
       *) # {{{
         local params=
@@ -81,7 +128,7 @@ rem() { # @@ # {{{
         do_use_file=true; do_set_store_env=true; do_append=true;;& # }}}
     --file | -f) # {{{
         file=
-        [[ -z $file ]] && [[ $2 == '-' ]] && file="$(getFileList -1 -t "$store_dir/${mask_file}*.txt")" && shift
+        [[ -z $file ]] && [[ $2 == '-' ]] && file="$(get-file-list -1 -t "$store_dir/${mask_file}*.txt")" && shift
         [[ -z $file ]] && [[ $2 == ${mask_file}* ]] && file="$store_dir/$2" && shift
         [[ -z $file ]] && [[ $2 == $store_dir/${mask_file}* ]] && file="$2" && shift
         [[ -z $file ]] && [[ ! -z $2 && -f $store_dir/$2 ]] && file="$store_dir/$2" && shift
@@ -110,11 +157,11 @@ rem() { # @@ # {{{
     --restore) # {{{
         do_restore=true
         local restore_file=
-        [[ -z $restore_file ]] && [[ $2 == '-' ]] && restore_file="$(getFileList -1 -t "$store_dir/${mask_file}*.txt-*.bck")" && shift
+        [[ -z $restore_file ]] && [[ $2 == '-' ]] && restore_file="$(get-file-list -1 -t "$store_dir/${mask_file}*.txt-*.bck")" && shift
         [[ -z $restore_file ]] && [[ $2 == ${mask_file}* ]] && restore_file="$store_dir/$2" && shift
         [[ -z $restore_file ]] && [[ $2 == $store_dir/${mask_file}* ]] && restore_file="$2" && shift
         [[ -z $restore_file ]] && [[ ! -z $2 && -f $store_dir/$2 ]] && restore_file="$store_dir/$2" && shift
-        [[ -z $restore_file ]] && restore_file="$(getFileList -1 -t "$store_dir/${mask_file}*.txt-*.bck")"
+        [[ -z $restore_file ]] && restore_file="$(get-file-list -1 -t "$store_dir/${mask_file}*.txt-*.bck")"
         ;; # }}}
     --smart)      do_smart=true;;
     # NO* # {{{
@@ -142,7 +189,7 @@ rem() { # @@ # {{{
     --) shift; p="$@"; shift $#; set -- "$p"; as_file=false; break;;
     -)  shift; break;;
     --help | --help-all) # {{{
-      cat <<-EOF >/dev/stdout
+      command cat <<-EOF >/dev/stdout
 					Switches:
 					  -1 | -2 | ...      - shows particular entry
 					  --append | -a      - append to temporary file
@@ -168,7 +215,7 @@ rem() { # @@ # {{{
 					  -- | -             - separate inputs from arguments, "-" does not threat inputs as files
 				EOF
       if [[ $1 == '--help-all' ]]; then # {{{
-        cat <<-EOF >/dev/stdout
+        command cat <<-EOF >/dev/stdout
 						  --no-*
 						    --no-append
 						    --no-abs
@@ -186,7 +233,7 @@ rem() { # @@ # {{{
 					EOF
       fi # }}}
       echo
-      cat <<-EOF >/dev/stdout
+      command cat <<-EOF >/dev/stdout
 					Defaults are:
 					  --no-reset -f --no-edit --keep --append --no-fzf --no-quiet --no-list --no-abs --no-restore --no-browse --no-cmd --no-ign
 				EOF
@@ -199,8 +246,8 @@ rem() { # @@ # {{{
   done # }}}
   # }}}
   if [[ ! -z $do_block_reset ]]; then # {{{
-    var="${var}_CONF_BLOCK_RESET"
-    eval export $var="$do_block_reset"
+    local -n var="${var}_CONF_BLOCK_RESET"
+    var="$do_block_reset"
     return 0
   else
     do_block_reset="${var}_CONF_BLOCK_RESET"
@@ -211,10 +258,10 @@ rem() { # @@ # {{{
   [[ -z $file ]] && file="$store_dir/${mask_file}.txt"
   if $do_browse; then # {{{
     local files=
-    files+=" $(getFileList "$store_dir/${mask_file}*.txt")"
-    files+=" $(getFileList "$store_dir/${mask_file}*.txt-*.bck")"
+    files+=" $(get-file-list "$store_dir/${mask_file}*.txt")"
+    files+=" $(get-file-list "$store_dir/${mask_file}*.txt-*.bck")"
     local res=
-    res="$(echo -e "$files" | sed -e 's/ /\n/g' | sed -e '/^\s*$/d' | fzf --height 100% --no-multi --preview-window 'right' --preview="sed 's/%20/ /g' {1} | cat -n")"
+    res="$(echo -e "$files" | sed -e 's/ /\n/g' | sed -e '/^\s*$/d' | fzf --height 100% --no-multi --preview-window 'right' --preview="sed 's/%20/ /g' {1} | command cat -n")"
     [[ $? != 0 || -z $res ]] && return 0
     if [[ $res == *.bck ]]; then
       do_restore=true
@@ -225,31 +272,31 @@ rem() { # @@ # {{{
     fi
   fi # }}}
   if $do_restore; then # {{{
-    [[ ! -e $restore_file ]] && echo "File to restore from [$restore_file] does not exist" >/dev/stderr && return 1
+    [[ ! -e $restore_file ]] && eval $(die "file to restore from [$restore_file] does not exist")
     [[ -e $file ]] && mv "$file" "${file}-$(command date +"$DATE_FMT").bck"
     mv "$restore_file" "$file"
   fi # }}}
-  var_use_file="${var}_USE_FILE"; var_file="${var}_FILE"
+  local -n var_use_file="${var}_USE_FILE"
+  local -n var_file="${var}_FILE"
+  local -n var="${var}_SRC"
   var="${var}_SRC"
   if $do_set_store_env; then # {{{
     if $do_use_file; then
-      eval $var_use_file="\"true\"" # for vim syntax: "
-      eval $var_file="\"$file\"" # for vim syntax: "
+      var_use_file="true"
+      var_file="$file"
     else
-      eval $var_use_file="\"false\"" # for vim syntax: "
-    fi
-    # }}}
+      var_use_file="false"
+    fi # }}}
   else # {{{
-    local u="${!var_use_file}"
-    if [[ $u == "false" || $u == "true" ]]; then
-      do_use_file="$u"
-      $do_use_file && file="${!var_file}"
-    fi
+    case $var_use_file in false|true)
+      do_use_file="$var_use_file"
+      $do_use_file && file="$var_file"
+    esac
   fi # }}}
   $do_append && do_use_file=true
   $do_edit && do_use_file=true
   if $do_reset; then # {{{
-    $do_block_reset && echo "Reset blocked" >/dev/stderr && return 1
+    $do_block_reset && eval $(die "reset blocked")
     if $do_use_file && [[ -e $file ]]; then
       mv "$file" "${file}-$(command date +"$DATE_FMT").bck"
       local to_rem=
@@ -257,9 +304,9 @@ rem() { # @@ # {{{
         && to_rem="$(ls ${file}-*.bck | /usr/bin/tail -r | sed "1,${keep_n_bck_files} d")" \
         || to_rem="$(ls ${file}-*.bck | head -n -$keep_n_bck_files)" 
       [[ ! -z "$to_rem" ]] && rm $to_rem
-      command find $(dirname $file) -maxdepth 1 -name "${mask_file}\*.bck" -empty -delete
+      find $(dirname $file) -maxdepth 1 -name "${mask_file}\*.bck" -empty -delete
     fi
-    eval $(eval "$reset_conf")
+    __rem-reset-conf
   fi # }}}
   $do_fzf && do_keep=true
   # What to do # {{{
@@ -273,54 +320,9 @@ rem() { # @@ # {{{
   [[ -z $mode ]] && mode='recall'
   # }}}
   if [[ "$mode" == 'add' ]]; then # Remember files # {{{
-    eval $var=''
+    var=
     [[ -z $fzf_prompt ]] && fzf_prompt="To store> "
-    last_working_path=
-    getItem() { # {{{
-      local p= i="$1" path=
-      i="${i//	/ /}"
-      if $do_split && [[ $i == *\ * ]]; then
-        set -- $i
-        local added=false
-        for i; do
-          getItem "$i"
-          [[ $? == 0 ]] && ! $added && added=true
-        done
-        ! $added && return 1
-        return 0
-      fi
-      if $as_file; then # {{{
-        [[ $i == ${tild}* ]] && i="${i/$tild/$HOME}"
-        if [[ $i == '..' ]]; then
-          p="$PWD"
-        elif [[ -e $i || -h $i ]]; then
-          [[ $i == /* ]] && p="$i" || path="$PWD"
-        elif [[ ! -z $last_working_path && -e "$last_working_path/$i" ]]; then
-          path="$last_working_path"
-        else
-          local path="$PWD"
-          while [[ ! -e "$path/$i" ]]; do
-            path="$(command cd "$path/.."; pwd)"
-            [[ $path == '/' || $path == "$HOME" ]] && break
-          done
-          [[ -e "$path/$i" ]] && last_working_path="$d" || path=
-        fi
-        [[ ! -z $path ]] && p="$path/$i"
-        if ${add_not_exst:-true}; then
-          [[ -z $p ]] && p="$i"
-        elif [[ ! -e $p ]]; then
-          p=""
-        fi
-        p="${p/$HOME/$tild}"
-        p="${p//\/.\//\/}"
-        # }}}
-      else # {{{
-        p="$i"
-      fi # }}}
-      [[ -z $p ]] && return 1
-      eval $var+="\"${p// /%20} \""
-      return 0
-    } # }}}
+    local last_working_path=
     if [[ -t 0 ]]; then # {{{
       if [[ -z $1 ]] && $do_ls; then # {{{
         local c=
@@ -330,18 +332,18 @@ rem() { # @@ # {{{
                 ;;
         rec-all) c="command find . -mindepth 1 \( -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2>/dev/null | cut -b3-";;
         1)       c="ls -A";;
-        *)       echo "ls mode [$ls_mode] not yet known" >/dev/stderr && return 1;;
+        *)       eval $(die "ls mode [$ls_mode] not yet known");;
         esac
         c+=" | fzf --height 100% --prompt '$fzf_prompt'"
         set -- $(eval "$c")
       fi # }}}
       for i; do # {{{
-        getItem "$i"
+        __rem-get-item "$i"
       done # }}}
       # }}}
     else # {{{
       local tmpFile="$TMP_MEM_PATH/rem/rem-$$.tmp"
-      [[ ! -e "${tmpFile%/*}" ]] && command mkdir "${tmpFile%/*}"
+      [[ ! -e "${tmpFile%/*}" ]] && command mkdir -p "${tmpFile%/*}"
       rm -f $tmpFile && touch $tmpFile
       while read i; do
         echo "$i" >> $tmpFile
@@ -356,7 +358,7 @@ rem() { # @@ # {{{
           i="\"${i//	/\" \"}\""
           eval set -- $i
           for j; do
-            getItem "$j"
+            __rem-get-item "$j"
             [[ $? == 0 ]] && ! $added && added=true
           done
         done < $tmpFile # }}}
@@ -371,14 +373,17 @@ rem() { # @@ # {{{
       done # }}}
       rm -f $tmpFile
     fi # }}}
-    unset getItem last_working_path
     if $do_use_file; then # {{{
-      $do_append && [[ -e $file ]] && eval $var="\"$(cat $file) ${!var}\""
-      echo "${!var}" | tr ' ' '\n' | sed '/^\s*$/ d' >$file
-      [[ ! -e $file ]] && touch $file
-      cat -n $file | sort -k2,2 -u | sort -k1,1 | awk '{print $2}' >$file.tmp
+      (
+        $do_append && [[ -e $file ]] && command cat $file
+        echo -e "$var"
+      ) \
+      | sed '/^\s*$/ d' \
+      | command cat -n - | sort -k2,2 -u | sort -k1,1 | cut -c8- \
+      >$file.tmp
       mv $file.tmp $file
       echo >>$file
+      var="$(<$file)"
     fi # }}}
   fi # }}}
   if [[ ! -t 1 ]] || $do_cmd; then
@@ -387,39 +392,34 @@ rem() { # @@ # {{{
   if [[ "$mode" == 'recall' ]]; then # Show remembered files # {{{
     if $do_edit; then # {{{
       local err=
-      sed -i -e 's/^\s\+//' -e 's/\s\+$//' -e 's/%20/ /g' $file
       $EDITOR $file </dev/tty >/dev/tty
       err=$?
-      sed -i -e 's/ /%20/g' $file
-      [[ $err != 0 ]] && { $do_quiet || echo "Error when editing" >/dev/stderr; return 1; }
+      [[ $err == 0 ]] || eval $(die -s=$do_quiet "error when editing")
     fi # }}}
     if $do_use_file; then # {{{
-      eval $var=
-      [[ -e $file ]] && eval $var="\"$(cat $file | tr '\n' ' ')\""
+      [[ -e $file ]] || eval $(die -s=$do_quiet "no file [$file]")
+      var="$(< $file)"
     fi # }}}
-    if [[ -z ${!var} ]]; then # {{{
+    if [[ -z $var ]]; then # {{{
       ( $do_reset || $do_use_file ) && return 0
-      $do_quiet || echo "No files remembered" >/dev/stderr
-      return 1
+      eval $(die -s=$do_quiet "no files remembered")
     fi # }}}
-    set -- ${!var}
     [[ -z $fzf_prompt ]] && fzf_prompt="To recall> "
-    for i; do # {{{
-      p="${i//%20/ }" && p="${p/$tild/$HOME}"
+    echo -e "$var" | while read -r p; do # {{{
       $show_abs || p="${p/$PWD/.}"
       echo "$p"
     done | \
     if $do_fzf; then
       fzf --height 100% --prompt "$fzf_prompt"
     else
-      cat -
+      command cat -
     fi | \
     if $do_cmd; then
-      xargs -ri $cmd
+      xargs -rI{} $cmd
     elif [[ ! -z $line_no ]]; then
       sed -n -e "${line_no}p"
     else
-      cat -
+      command cat -
     fi
     # }}}
     if ! $do_keep; then # {{{
@@ -430,9 +430,9 @@ rem() { # @@ # {{{
           && to_rem="$(ls ${file}-*.bck | /usr/bin/tail -r | sed "1,${keep_n_bck_files} d")" \
           || to_rem="$(ls ${file}-*.bck | head -n -$keep_n_bck_files)" 
         [[ ! -z "$to_rem" ]] && rm $to_rem
-        command find $(dirname $file) -maxdepth 1 -name "${mask_file}\*.bck" -empty -delete
+        find $(dirname $file) -maxdepth 1 -name "${mask_file}\*.bck" -empty -delete
       fi
-      eval $(eval $reset_conf)
+      __rem-reset-conf
     fi # }}}
   fi # }}}
   return 0
diff --git a/bash/colors b/bash/colors
--- a/bash/colors
+++ b/bash/colors
@@ -11,14 +11,16 @@ export RCSTUFF_COLORS_INSTALLED=true
 # }}}
 # Env # {{{
 export COLORS_BASIC_LIST="" # IGN
-export COLORS_BASIC_LIST+=" black   red   green   yellow   blue   purple   cyan   white  gold  gray  off"   # IGN
-export COLORS_BASIC_LIST+=" CBlack  CRed  CGreen  CYellow  CBlue  CPurple  CCyan  CWhite CGold CGray COff"  # IGN
-export COLORS_BASIC_LIST+=" CIBlack CIRed CIGreen CIYellow CIBlue CIPurple CICyan CIWhite"                  # IGN
+export COLORS_BASIC_LIST+=" black    red    green    yellow    blue    purple    magenta    cyan    white    gold  gray  off"   # IGN
+export COLORS_BASIC_LIST+=" CBlack   CRed   CGreen   CYellow   CBlue   CPurple   CMagenta   CCyan   CWhite   CGold CGray COff"  # IGN
+export COLORS_BASIC_LIST+=" CIBlack  CIRed  CIGreen  CIYellow  CIBlue  CIPurple  CIMagenta  CICyan  CIWhite"                  # IGN
+export COLORS_BASIC_LIST+=" CBBlack  CBRed  CBGreen  CBYellow  CBBlue  CBPurple  CBMagenta  CBCyan  CBWhite"                  # IGN
+export COLORS_BASIC_LIST+=" CBIBlack CBIRed CBIGreen CBIYellow CBIBlue CBIPurple CBIMagenta CBICyan CBIWhite"                  # IGN
 export COLORS_BASIC_LIST+=" HLSearch GoldOrig"                                                              # IGN
 export COLORS_FILE="$BASHRC_RUNTIME_PATH/colors" # IGN
 if [[ $1 == '--force' ]] || ${RCSTUFF_FORCE:-false}; then # {{{
   [[ $1 == '--force' ]] && shift
-  rm -f $COLORS_FILE
+  rm -f $COLORS_FILE $COLORS_FILE.json
   unset colorCache
 fi # }}}
 if [[ -e $COLORS_FILE ]]; then
@@ -27,7 +29,8 @@ else
   declare -A -x colorCache=([off]="$COff")
   declare -A -x COLORS
   COLORS+=([err]="red" [ok]="green" [wrn]="purple" [info]="yellow" [i2]="cyan"); COLORS[i1]=${COLORS[info]}
-  COLORS+=([imp]="HLSearch" [imp2]="Gold")
+  COLORS+=([imp]="HLSearch" [imp2]="Gold" [magenta]="purple")
+  COLORS+=([hls-search]="HLSearch" [gold-orig]="GoldOrig")
   COLORS[ip]="yellow"
   COLORS[ts]="blue"
   COLORS[file]="cyan"
@@ -35,75 +38,7 @@ else
   COLORS[grey]="gray"
 fi
 # }}}
-colorCacheDump() { # {{{
-  [[ -e $COLORS_FILE ]] || colorCacheInit -s
-  if [[ -e $COLORS_FILE ]]; then # {{{
-    source $COLORS_FILE
-  else
-    ! declare -p colorCache >/dev/null 2>&1 && declare -A -x colorCache=([off]="$COff")
-    ! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap
-    ! declare -p COLORS >/dev/null 2>&1 && declare -A -x COLORS
-  fi # }}}
-  local i= w1=9 w2=-12 colors_ci= cOff="$(getColor --cached off)"
-  echor -C "%yellow:{colorCache}:"
-  for i in $(echo "${!colorCache[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
-    if [[ $i =~ ^CI[A-Z] ]]; then
-      colors_ci+="$i "
-      continue
-    fi
-    if [[ $i =~ ^C[A-Z] ]]; then
-      echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "$i") --"
-    else
-      if [[ ! -z $colors_ci ]]; then
-        local ii=
-        for ii in $colors_ci; do
-          echor "  $(printf "%${w1}s" "$ii") : -- $(printf "$(getColor --cached $ii)%${w2}s$cOff" "$ii") --"
-        done
-        colors_ci=
-      fi
-      echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "$i") --"
-    fi
-  done
-  echor -C "%yellow:{COLORS}:"
-  for i in $(echo "${!COLORS[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
-    echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "${COLORS[$i]}") --"
-  done
-  echor -C "%yellow:{colorsMap}:"
-  for i in $(echo "${!colorsMap[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
-    echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(getColor --cached $i)%${w2}s$cOff" "${COLORS[$i]}") --"
-  done
-} # }}}
-colorCacheInit() { # {{{
-  local i= k= verbose=false addSource=true
-  while [[ ! -z $1 ]]; do
-    case $1 in
-    -v) verbose=true;;
-    -s) addSource=false;;
-    esac; shift
-  done
-  for i in off $COLORS_BASIC_LIST ${!COLORS[*]} $@; do
-    [[ $i =~ ^[A-Za-z] ]] || continue
-    if $verbose; then
-      echo "$(getColor --cache $i)Storing1${COff}: $i"
-    else
-      getColor $i >/dev/null
-    fi
-  done
-  for i in ${!COLORS[*]}; do
-    i=${COLORS[$i]}
-    [[ $i =~ ^[A-Za-z] ]] || continue
-    if $verbose; then
-      echo "$(getColor --cache $i)Storing2${COff}: $i"
-    else
-      getColor $i >/dev/null
-    fi
-  done
-  if $addSource && [[ -e $COLORS_FILE ]]; then
-    source $COLORS_FILE
-  fi
-}
-export -f colorCacheInit # }}}
-colorList() { # {{{
+color-list() { # {{{
   local list=
   if [[ $1 == '--full' ]]; then
     list="$(awk -F'=' '/^ *export C[A-Z]/ && !/# IGN/ {print $1}'  $BASH_PATH/colors | sed 's/.*export //' | sort -u)"
@@ -125,18 +60,18 @@ colorList() { # {{{
     echo "$list"
   ) | tr ' ' '\n' | sed '/^ *$/d' | LC_COLLATE=C sort -u
 } # }}}
-getColor() { # {{{
+get-color() { # {{{
   if [[ $1 == '@@' ]]; then # {{{
     case $3 in
     -c | --color) # {{{
-      colorList --full;; # }}}
+      color-list --full;; # }}}
     -f | -b) # {{{
       seq 0 255;; # }}}
     -r | --raw) # {{{
       echo "-f -b -n --name FG-space-BG";; # }}}
     *) # {{{
       echo "-c --color -r --raw"
-      colorList;; # }}}
+      color-list;; # }}}
     esac
     return 0
   fi # }}}
@@ -201,11 +136,97 @@ getColor() { # {{{
   fi
   echo "$c"
 }
-export -f getColor
-complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic getColor # }}}
+complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic get-color # }}}
+color-cache-dump() { # {{{
+  [[ -e $COLORS_FILE ]] || color-cache-init -s
+  if [[ -e $COLORS_FILE ]]; then # {{{
+    source $COLORS_FILE
+  else
+    ! declare -p colorCache >/dev/null 2>&1 && declare -A -x colorCache=([off]="$COff")
+    ! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap
+    ! declare -p COLORS >/dev/null 2>&1 && declare -A -x COLORS
+  fi # }}}
+  local i= w1=12 w2=-15 colors_ci= colors_cb= colors_cbi= cOff="$(get-color --cached off)"
+  echor -C "%yellow:{colorCache}:"
+  for i in $(echo "${!colorCache[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
+    if [[ $i =~ ^CB[A-Z] ]]; then
+      colors_cb+="$i "
+      continue
+    elif [[ $i =~ ^CBI[A-Z] ]]; then
+      colors_cbi+="$i "
+      continue
+    elif [[ $i =~ ^CI[A-Z] ]]; then
+      colors_ci+="$i "
+      continue
+    fi
+    if [[ $i =~ ^C[A-Z] ]]; then
+      echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(get-color --cached $i)%${w2}s$cOff" "$i") --"
+    else
+      if [[ ! -z $colors_cb ]]; then
+        local ii=
+        for ii in $colors_cb; do
+          echor "  $(printf "%${w1}s" "$ii") : -- $(printf "$(get-color --cached $ii)%${w2}s$cOff" "$ii") --"
+        done
+        colors_cb=
+      fi
+      if [[ ! -z $colors_cbi ]]; then
+        local ii=
+        for ii in $colors_cbi; do
+          echor "  $(printf "%${w1}s" "$ii") : -- $(printf "$(get-color --cached $ii)%${w2}s$cOff" "$ii") --"
+        done
+        colors_cbi=
+      fi
+      if [[ ! -z $colors_ci ]]; then
+        local ii=
+        for ii in $colors_ci; do
+          echor "  $(printf "%${w1}s" "$ii") : -- $(printf "$(get-color --cached $ii)%${w2}s$cOff" "$ii") --"
+        done
+        colors_ci=
+      fi
+      echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(get-color --cached $i)%${w2}s$cOff" "$i") --"
+    fi
+  done
+  echor -C "%yellow:{COLORS}:"
+  for i in $(echo "${!COLORS[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
+    echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(get-color --cached $i)%${w2}s$cOff" "${COLORS[$i]}") --"
+  done
+  echor -C "%yellow:{colorsMap} (user):"
+  for i in $(echo "${!colorsMap[*]}" | tr ' ' '\n' | LC_COLLATE=C sort); do
+    echor "  $(printf "%${w1}s" "$i") : -- $(printf "$(get-color --cached $i)%${w2}s$cOff" "${COLORS[$i]}") --"
+  done
+} # }}}
+color-cache-init() { # {{{
+  local i= k= verbose=false addSource=true
+  while [[ ! -z $1 ]]; do
+    case $1 in
+    -v) verbose=true;;
+    -s) addSource=false;;
+    esac; shift
+  done
+  for i in off $COLORS_BASIC_LIST ${!COLORS[*]} $@; do
+    [[ $i =~ ^[A-Za-z] ]] || continue
+    if $verbose; then
+      echo "$(get-color --cache $i)Storing1${COff}: $i"
+    else
+      get-color $i >/dev/null
+    fi
+  done
+  for i in ${!COLORS[*]}; do
+    i=${COLORS[$i]}
+    [[ $i =~ ^[A-Za-z] ]] || continue
+    if $verbose; then
+      echo "$(get-color --cache $i)Storing2${COff}: $i"
+    else
+      get-color $i >/dev/null
+    fi
+  done
+  if $addSource && [[ -e $COLORS_FILE ]]; then
+    source $COLORS_FILE
+  fi
+} # }}}
 cl() { # {{{
   if [[ $1 == '@@' ]]; then # {{{
-    colorList
+    color-list
     if [[ $3 != '-C' ]]; then
       echo "- -- -C -f -F COLOR-space-STR COLOR:STR(space-added) COLOR::STR(no-space-added) --sep"
     fi
@@ -221,7 +242,7 @@ cl() { # {{{
     fi # }}}
   fi # }}}
   local coff=${colorCache[off]} cCurrent= verbose=false format=false asArray=false sep=" "
-  [[ -z $coff ]] && coff=$(getColor --cached off)
+  [[ -z $coff ]] && coff=$(get-color --cached off)
   while [[ ! -z $1 ]]; do # {{{
     case $1 in
     -v) verbose=true;;
@@ -230,7 +251,7 @@ cl() { # {{{
     --sep) sep="$2"; shift;;
     -C) # {{{
       shift
-      cCurrent=$(getColor --cached ${1%%:*}) || { $verbose && echo "Cannot find color for '${1%%:*}'" >/dev/stderr; }
+      cCurrent=$(get-color --cached ${1%%:*}) || { $verbose && echo "Cannot find color for '${1%%:*}'" >/dev/stderr; }
       ! $format && [[ $1 == *:* ]] && break;; # }}}
     *) break;;
     esac; shift
@@ -311,7 +332,7 @@ cl() { # {{{
           fi
           c="${colorCache[$n]}"
           if [[ -z $c ]]; then
-            c=$(getColor --cached $n) || { $verbose && echo "Cannot find color for '$n'" >/dev/stderr; }
+            c=$(get-color --cached $n) || { $verbose && echo "Cannot find color for '$n'" >/dev/stderr; }
             colorCache[$n]="$c"
           fi
           cLast=$c # }}}
@@ -387,7 +408,7 @@ if [[ $TERM_ORIG == 'linux' ]]; then # {{{
   export CBIGreen="$CGreen"
   export CBIYellow="$CYellow"
   export CBIBlue="$CBlue"
-  export CBIPurple="$CPurple"
+  export CBIPurple="$CBIPurple"
   export CBICyan="$CCyan"
   export CBIWhite="$CWhite" # }}}
 else # {{{
@@ -445,6 +466,7 @@ else # {{{
   export COnYellow='[43m'
   export COnBlue='[44m'
   export COnPurple='[45m'
+  export COnMagenta="$COnPurple"
   export COnCyan='[46m'
   export COnWhite='[47m'
   # }}}
@@ -455,17 +477,41 @@ else # {{{
   export COnIYellow='[0;103m'
   export COnIBlue='[0;104m'
   export COnIPurple='[10;95m'
+  export COnIMagenta="$COnIPurple"
   export COnICyan='[0;106m'
   export COnIWhite='[0;107m'
   # }}}
 fi # }}}
+# Aliases # {{{
+export CMagenta="$CPurple"
+export CBMagenta="$CPurple"
+export CUMagenta="$CUPurple"
+export CIMagenta="$CIPurple"
+export CBIMagenta="$CBIPurple"
+# }}}
 # Env, cont. # {{{
 if [[ ! -e $COLORS_FILE ]]; then
   touch $COLORS_FILE
   declare -p COLORS >>$COLORS_FILE
   echo "! declare -p colorsMap >/dev/null 2>&1 && declare -A -x colorsMap" >>$COLORS_FILE
-  colorCacheInit -s
-fi
+  color-cache-init -s
+  if which jq >/dev/null 2>&1; then
+    (
+      source $COLORS_FILE
+      for i in ${!COLORS[*]}; do
+        c=${COLORS[$i]}
+        [[ $c == *[* ]] && c="[${c#*[}"
+        echo -e "\"$i\"\n\"$c\""
+      done
+      for i in ${!colorCache[*]}; do
+        c=${colorCache[$i]}
+        [[ $c == *[* ]] && c="[${c#*[}"
+        echo -e "\"$i\"\n\"$c\""
+      done
+    ) | jq -n 'reduce inputs as $i ({}; . + { ($i): input })' >$COLORS_FILE.json
+  fi
+fi # }}}
+export -f color-cache-init get-color cl printfc echoc
 source $COLORS_FILE
 true
-# }}}
+
diff --git a/bash/completion b/bash/completion
--- a/bash/completion
+++ b/bash/completion
@@ -42,23 +42,23 @@ compl-short() { # {{{
   echorv -M 1 tool
   local list="$(
     for i in $($tool @@ -- | tr ' ' '\n'); do
-      [[ $i == --?* ]] || { echorm 3 "skip:[$i]"; continue; }
+      [[ $i == --?* ]] || { echorm -m compl-short 3 "skip:[$i]"; continue; }
       echo "$(echo "$i" | sed -n 's/-\+\([a-z]\)[^-]*/\1/gp') $i"
     done | sort)"
   $addShorts && list="$(echo -e "$list\n$($tool @@ --shorts)")"
-  echorm 2 "list-pre:[$(echo "$list" | tr '\n' ':')]"
+  echormf 2 "list-pre:[$(echo "$list" | tr '\n' ':')]"
   local sLast= s= f= toRemove= remove=false i=
   while read s f; do # {{{
     remove=false
-    [[ $s == $sLast ]] && remove=true && echorm 3 "checking $s [$f]: the same [= $sLast]"
-    [[ ${#s} -lt $len && $s =~ ^[a-z] ]] && remove=true && echorm 3 "checking $s [$f]: too short [< $len]"
-    $remove && toRemove+="\|^$s " || echorm 3 "checking $s [$f]: ok"
+    [[ $s == $sLast ]] && remove=true && echormf 3 "checking $s [$f]: the same [= $sLast]"
+    [[ ${#s} -lt $len && $s =~ ^[a-z] ]] && remove=true && echormf 3 "checking $s [$f]: too short [< $len]"
+    $remove && toRemove+="\|^$s " || echormf 3 "checking $s [$f]: ok"
     sLast=$s
   done < <(echo "$list") # }}}
   toRemove="${toRemove#\\|}"
-  echorv -M 2 toRemove
-  [[ -z $toRemove ]] || list="$(echo "$list" | grep -v "$toRemove")"
-  echorm 1 "list-post:[$(echo "$list" | tr '\n' ':'))]"
+  echormf -f? && echorv -M 2 toRemove
+  [[ -z $toRemove ]] || list="$(echo "$list" | command grep -v "$toRemove")"
+  echormf 1 "list-post:[$(echo "$list" | tr '\n' ':'))]"
   while read s f; do
     s=${s#!}
     case $wtd in
@@ -93,6 +93,7 @@ compl-help() { # {{{
   if [[ $1 == @@ ]]; then # {{{
     echo "$EXPORTED_FUNCTIONS"
     echo "-s --short -l --long @@-f @@-d"
+    declare -Fx | cut -d' ' -f3 | command grep -v "^_"
     return 0
   fi # }}}
   local cmd= short=false
@@ -104,27 +105,32 @@ compl-help() { # {{{
     esac; shift
   done # }}}
   if [[ -z $cmd && ! -t 0 ]]; then
-    cmd="$(cat -)"
+    cmd="$(<-)"
   elif [[ -e "$cmd" ]]; then
-    cmd="$(cat "$cmd")"
+    cmd="$(<"$cmd")"
   elif ! declare -F "$cmd" >/dev/null 2>&1; then
     cmd="$(which "$cmd")"
-    cmd="$(cat "$cmd")"
+    cmd="$(<"$cmd")"
   else
     cmd="$(type "$cmd")"
+    if [[ $cmd =~ (\$ALIASES_SCRIPTS/[^ ]*) ]]; then
+      local f=${BASH_REMATCH[1]}
+      f="$(eval echo "$f")"
+      cmd="$(<$f)"
+    fi
   fi
   local indent="$(echo "$cmd" | command grep '^ *while \[\[ ! -z $1 \]\]; do' | head -n1 | command grep -o "^ *")"
-  local parser="$(echo "$cmd" | sed -n '/'"^$indent"'while/,/'"^$indent"'done/p' | cat -n)"
-  local caseS="$(echo "$parser" | cat | awk '/case/ {print $1}' | head -n1)"
+  local parser="$(echo "$cmd" | sed -n '/'"^$indent"'while/,/'"^$indent"'done/p' | command cat -n)"
+  local caseS="$(echo "$parser" | command cat | awk '/case/ {print $1}' | head -n1)"
   local caseE="$(echo "$parser" | tac | awk '/esac/ {print $1}' | head -n1)"
   caseS=$((caseS+1)) caseE=$((caseE-1))
   parser="$(echo "$parser" | sed -n "$caseS,$caseE p" | cut -c9-)"
   indent="$(echo "$parser" | head -n1 | command grep -o "^ *")"
   parser="$(echo "$parser" | sed 's/^'"$indent"'//')"
   if $short; then
-    echo "$parser" | command grep "^[^ ][^)]*)" | sed 's/).*//' | { if [[ -t 1 ]] && isInstalled column; then column -t; else cat -; fi; }
+    echo "$parser" | command grep "^[^ ][^)]*)" | sed 's/).*//' | { if [[ -t 1 ]] && is-installed column; then column -t; else command cat -; fi; }
   else
-    echo "$parser" | sed -e '/^;;/d' -e 's/;$//' | hl +c=Search "^[^ ][^)]*)"
+    echo "$parser" | sed -e '/^;;/d' -e 's/;$//' | hl-bash +c=Search "^[^ ][^)]*)"
   fi
 }
 alias ch='compl-help'
@@ -188,39 +194,37 @@ if $IS_MAC; then
   fi
 fi # }}}
 # Completion for git aliases defined in git-cmds.sh # {{{
-for i in $($SCRIPT_PATH/git/git-cmds.sh --comply); do
-  eval "_git_${i}() { _completion_generic; }"
+for ii in $($SCRIPT_PATH/git/git-cmds.sh --comply); do
+  eval "_git_${ii}() { _completion_generic; }"
 done
 # }}}
 # Set generic completion # {{{
 COMPLETION_GENERIC_UTILS+=" fix_ssh_agent.sh mk_tar.sh asciidoc2html.sh gitst do_sync.sh tmux-startup.sh vim-enc.sh"
 COMPLETION_GENERIC_UTILS+=" repo.sh repo-get-diff.sh repo-update.sh"
-for i in $COMPLETION_GENERIC_UTILS $TO_INSTALL_BIN_MISC; do
-  type $i >/dev/null 2>&1 && complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic $i # || echo "Util [$i] not found" >/dev/stderr
+for ii in $COMPLETION_GENERIC_UTILS $TO_INSTALL_BIN_MISC; do
+  type $ii >/dev/null 2>&1 && complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic $ii # || echo "Util [$ii] not found" >/dev/stderr
 done
-unset COMPLETION_GENERIC_UTILS
-for i in $(echo "$COMPLETION_GENERIC_FUNCTIONS" | tr ' ' '\n' | sort -u | tr '\n' ' '); do
-  if type $i >/dev/null 2>&1; then
-    complete -r $i >/dev/null 2>&1
-    complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic $i
+for ii in $(echo "$COMPLETION_GENERIC_FUNCTIONS" | tr ' ' '\n' | sort -u | tr '\n' ' '); do
+  if type $ii >/dev/null 2>&1; then
+    complete -r $ii >/dev/null 2>&1
+    complete $COMPLETE_DEFAULT_PARAMS -F _completion_generic $ii
   else
-    echo "Function [$i] not found" >/dev/stderr
+    echo "Function [$ii] not found" >/dev/stderr
   fi
 done
-list="$(complete)"
+unset COMPLETION_GENERIC_UTILS COMPLETION_GENERIC_FUNCTIONS
 set +f
-for i in $HOME/.bin/*.sh; do
-  i="${i##*/}"
-  compl-add "$i"
+for ii in $HOME/.bin/*.sh; do
+  ii="${ii##*/}"
+  compl-add "$ii"
 done
-unset COMPLETION_GENERIC_FUNCTIONS
 # }}}
 # Git-cmds # {{{
 complete $COMPLETE_DEFAULT_PARAMS -F _completion_git_cmds git_cmds.sh
 # }}}
 # Hosts # {{{
 if [[ -e $HOME/.ssh/known_hosts ]] && tail -1 $HOME/.ssh/known_hosts | command grep -vq "^|1|"; then
-  complete -W "$( echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | command grep -v "\["`;)" ssh
+  complete -W "$( echo `command cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | command grep -v "\["`;)" ssh
 fi # }}}
 # Vim # {{{
 _do_vim_completion
@@ -228,6 +232,7 @@ unset _do_vim_completion
 # }}}
 # Oth # {{{
 complete | command grep -q " cdd$" || complete $COMPLETE_DEFAULT_PARAMS -W "$(cd_wrapper -- @@ - -i | tr '\n' ' ')" cdd
+declare -F _filedir >/dev/null && eval "$(type -a _filedir | tail -n +2 | sed 's/compopt -o filenames 2>/compopt -o filenames -o noquote 2>/')"
 # }}}
 # tldr # {{{
 if [[ -e $HOME/.local/share/tldr ]]; then
@@ -235,16 +240,17 @@ if [[ -e $HOME/.local/share/tldr ]]; then
 fi # }}}
 # Source additional completions # {{{
 if [[ -e $BASH_PATH/completion.d ]]; then
-  for i in $(ls $BASH_PATH/completion.d); do
-    [[ -f $BASH_PATH/completion.d/$i ]] && source $BASH_PATH/completion.d/$i
+  for ii in $(ls $BASH_PATH/completion.d); do
+    [[ -f $BASH_PATH/completion.d/$ii ]] && source $BASH_PATH/completion.d/$ii
   done
 fi
 if [[ -e $RUNTIME_PATH/completion.d ]]; then
-  for i in $(ls $RUNTIME_PATH/completion.d); do
-    [[ -f $RUNTIME_PATH/completion.d/$i && ( -x $RUNTIME_PATH/completion.d/$i || $i == *.sh || $i == *.bash ) ]] && source $RUNTIME_PATH/completion.d/$i
+  for ii in $(ls $RUNTIME_PATH/completion.d); do
+    [[ -f $RUNTIME_PATH/completion.d/$ii && ( -x $RUNTIME_PATH/completion.d/$ii || $ii == *.sh || $ii == *.bash ) ]] && source $RUNTIME_PATH/completion.d/$ii
   done
 fi
 # }}}
+unset ii
 # Source profile specic completions # {{{
 for profi in $BASH_PROFILES_FULL; do
   [[ -e $profi/completion ]] && source $profi/completion
