S#006

diff --git a/bash/runtime-post b/bash/runtime-post
--- a/bash/runtime-post
+++ b/bash/runtime-post
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # vim: fdl=0
 
 # Is installed # {{{
@@ -70,10 +70,13 @@ if ${REMOTE_CHANGES_APPLY:-false} && [[ ! -z $SHARED_BASH_PATH && -d $src_dir ]]
         j="$TMP_MEM_PATH/${file%.enc}"
         if [[ ! -z $REMOTE_CHANGES_KEY ]]; then
           p="--key '$REMOTE_CHANGES_KEY'"
-        else
+        elif [[ ! -z $REMOTE_CHANGES_PWD ]]; then
           p="--pass '$($PROFILES_PATH/home/bin/oth/runtime-pwd.sh -q "$REMOTE_CHANGES_PWD")'"
+        else
+          echo "Missing passphrase for [$file]"
+          continue
         fi
-        if ! eval $BASH_PATH/aliases encryptor $p "$i" "$j"; then
+        if ! eval $ALIASES encryptor $p "$i" "$j"; then
           echo "Cannot decrypt [$file]"
           continue
         fi
@@ -93,6 +96,18 @@ unset REMOTE_CHANGES_APPLY REMOTE_CHANGES_ALLOW_PLAIN REMOTE_CHANGES_PWD REMOTE_
 # Check personalities # {{{
 [[ -z $PERS_USERS ]] && echo "Personalities not found!!!" >/dev/stderr && sleep 2
 # }}}
+# Unicode extra chars # {{{
+if [[ ! -z "$UNICODE_EXTRA_CHARS_FILE" && ! -e "$UNICODE_EXTRA_CHARS_FILE" ]]; then
+  touch "$UNICODE_EXTRA_CHARS_FILE"
+  {
+    echo "declare -A UNICODE_EXTRA_CHARS"
+    for i in $(echo ${!UNICODE_EXTRA_CHARS[*]} | tr ' ' '\n' | sort); do
+      echo "UNICODE_EXTRA_CHARS[$i]=\"${UNICODE_EXTRA_CHARS[$i]}\""
+    done
+    echo
+  } >"$UNICODE_EXTRA_CHARS_FILE"
+  unset i
+fi # }}}
 if $IS_MAC; then # {{{
   [[ -z $PS1_CURSOR_COLOR ]] && PS1_CURSOR_COLOR=false
 fi # }}}
